// Everything you can carry, buy, cook or put down.
//
// Written by the editor in tools/editor. Everything in here is data: no
// functions, no imports, nothing that cannot survive a round trip through
// JSON. Hand edits are welcome and will be kept, but the formatting and any
// comments outside this header are replaced the next time the editor saves.
// A prose note about a particular entry belongs in its own `note` field,
// which is data and does survive.

export const ITEM_DATA = {
  house_coffee: {
    name: 'House Coffee',
    desc: "It's dependable. Nobody has ever complained about it, which is its own kind of praise.",
    cat: 'drink',
    icon: 'coffee',
    cost: 4,
    price: 12,
    appeal: 1,
    temp: 'hot',
    shelf: 8,
  },
  espresso: {
    name: 'Espresso',
    desc: "It's small, dark, and extremely serious.",
    cat: 'drink',
    icon: 'espresso',
    cost: 5,
    price: 16,
    appeal: 1.15,
    temp: 'hot',
    shelf: 8,
  },
  latte: {
    name: 'Latte',
    desc: "There's a cat face in the foam, and it takes you nine tries every time.",
    cat: 'drink',
    icon: 'latte',
    cost: 7,
    price: 21,
    appeal: 1.3,
    temp: 'hot',
    shelf: 4,
  },
  black_tea: {
    name: 'Black Tea',
    desc: "It's strong enough to stand a spoon in, if that's how you like it.",
    cat: 'drink',
    icon: 'tea',
    cost: 3,
    price: 11,
    appeal: 1,
    temp: 'hot',
    shelf: 24,
  },
  herbal_tea: {
    name: 'Herbal Tea',
    desc: "It's mostly chamomile, and people keep falling asleep in the window seat.",
    cat: 'drink',
    icon: 'herbal',
    cost: 5,
    price: 17,
    appeal: 1.2,
    temp: 'hot',
    shelf: 24,
  },
  matcha: {
    name: 'Matcha',
    desc: "It's bright green and quietly expensive.",
    cat: 'drink',
    icon: 'matcha',
    cost: 9,
    price: 27,
    appeal: 1.5,
    temp: 'hot',
    shelf: 14,
  },
  cocoa: {
    name: 'Hot Cocoa',
    desc: 'It comes with two marshmallows, or three if you like them.',
    cat: 'drink',
    icon: 'cocoa',
    cost: 6,
    price: 19,
    appeal: 1.3,
    temp: 'hot',
    shelf: 12,
  },
  lemonade: {
    name: 'Lemonade',
    desc: "It's made fresh, which is why it never lasts.",
    cat: 'drink',
    icon: 'lemonade',
    cost: 4,
    price: 14,
    appeal: 1.1,
    temp: 'cold',
    shelf: 4,
  },
  milk: {
    name: 'Warm Milk',
    desc: 'The cats get extremely interested whenever you pour it.',
    cat: 'drink',
    icon: 'milk',
    cost: 3,
    price: 9,
    appeal: 0.95,
    temp: 'hot',
    shelf: 3,
  },
  dandelion: {
    name: 'Dandelion Cordial',
    desc: "It's made from a weed by somebody who knows exactly which weed, and it tastes like a field in June.",
    cat: 'drink',
    icon: 'dandelion',
    cost: 6,
    price: 19,
    appeal: 1.35,
    temp: 'cold',
    shelf: 14,
  },
  iced_coffee: {
    name: 'Iced Coffee',
    desc: "It's served over lots of ice in a tall glass, for the one week a year when it's hot enough.",
    cat: 'drink',
    icon: 'icedCoffee',
    cost: 5,
    price: 17,
    appeal: 1.2,
    temp: 'cold',
    shelf: 3,
  },
  iced_tea: {
    name: 'Iced Tea',
    desc: 'It comes with a slice of lemon balanced on the rim, which nobody ever eats.',
    cat: 'drink',
    icon: 'icedTea',
    cost: 4,
    price: 15,
    appeal: 1.15,
    temp: 'cold',
    shelf: 3,
  },
  cider: {
    name: 'Cloudy Cider',
    desc: "It's pressed from the orchard up the valley, and it's very cloudy and very good.",
    cat: 'drink',
    icon: 'cider',
    cost: 8,
    price: 24,
    appeal: 1.4,
    temp: 'cold',
    shelf: 20,
  },
  smoked_tea: {
    name: 'Smoked Lapsang',
    desc: "It tastes like a bonfire in the best possible way. Not everyone loves it, but it's very profitable.",
    cat: 'drink',
    icon: 'tea',
    cost: 14,
    price: 42,
    appeal: 1.95,
    temp: 'hot',
    shelf: 24,
    rare: true,
  },
  cookie: {
    name: 'Butter Cookie',
    desc: "It's shaped like a paw, badly but sincerely.",
    cat: 'food',
    icon: 'cookie',
    cost: 3,
    price: 10,
    appeal: 1,
    shelf: 10,
  },
  scone: {
    name: 'Scone',
    desc: "The jam goes on first. In this valley, that's not negotiable.",
    cat: 'food',
    icon: 'scone',
    cost: 5,
    price: 16,
    appeal: 1.2,
    shelf: 3,
  },
  croissant: {
    name: 'Croissant',
    desc: 'It leaves flakes everywhere, and the cats consider that a feature.',
    cat: 'food',
    icon: 'croissant',
    cost: 6,
    price: 18,
    appeal: 1.3,
    shelf: 2,
  },
  muffin: {
    name: 'Berry Muffin',
    desc: "It's full of berries from the hedgerow, and you picked most of them yourself.",
    cat: 'food',
    icon: 'muffin',
    cost: 5,
    price: 15,
    appeal: 1.15,
    shelf: 3,
  },
  sandwich: {
    name: 'Sandwich',
    desc: "It's cut into triangles, because squares are for weekdays.",
    cat: 'food',
    icon: 'sandwich',
    cost: 7,
    price: 20,
    appeal: 1.2,
    shelf: 2,
  },
  toast: {
    name: 'Honey Toast',
    desc: "It's cut thick and dripping with honey. This is deeply unserious food.",
    cat: 'food',
    icon: 'toast',
    cost: 6,
    price: 19,
    appeal: 1.3,
    temp: 'hot',
    shelf: 2,
  },
  cake: {
    name: 'Sponge Cake',
    desc: 'The slices are big enough to justify a second visit.',
    cat: 'food',
    icon: 'cake',
    cost: 9,
    price: 28,
    appeal: 1.55,
    shelf: 3,
  },
  pancakes: {
    name: 'Pancake Stack',
    desc: 'Pancakes are weekend food, and people come in just for them.',
    cat: 'food',
    icon: 'pancakes',
    cost: 8,
    price: 25,
    appeal: 1.45,
    temp: 'hot',
    shelf: 1,
  },
  parfait: {
    name: 'Berry Parfait',
    desc: "It's layered in a tall glass so it looks like it took effort.",
    cat: 'food',
    icon: 'parfait',
    cost: 11,
    price: 32,
    appeal: 1.65,
    temp: 'cold',
    shelf: 2,
  },
  pie: {
    name: 'Fruit Pie',
    desc: "It's a whole pie sold by the slice, and it's gone by three.",
    cat: 'food',
    icon: 'pie',
    cost: 12,
    price: 36,
    appeal: 1.75,
    temp: 'hot',
    shelf: 4,
  },
  honey_scone: {
    name: 'Honey Scone',
    desc: "It's made with Clover's honey and served warm from the oven. People have written letters about it.",
    cat: 'food',
    icon: 'scone',
    cost: 8,
    price: 26,
    appeal: 1.6,
    temp: 'hot',
    shelf: 3,
    rare: true,
  },
  ice_cream: {
    name: 'Ice Cream',
    desc: "It's two scoops, and it melts faster than anybody plans for.",
    cat: 'food',
    icon: 'iceCream',
    cost: 6,
    price: 20,
    appeal: 1.35,
    temp: 'cold',
    shelf: 2,
  },
  fishcake: {
    name: 'Fishcake',
    desc: 'Every cat in the building will supervise you making these.',
    cat: 'food',
    icon: 'fishcake',
    cost: 10,
    price: 30,
    appeal: 1.5,
    temp: 'hot',
    shelf: 2,
  },
  kibble: {
    name: 'Everyday Kibble',
    desc: 'It keeps a cat alive and mildly disappointed.',
    cat: 'catfood',
    icon: 'catfood',
    cost: 8,
    quality: 1,
    portions: 6,
    shelf: 30,
  },
  good_food: {
    name: 'Good Cat Food',
    desc: 'Coats get glossier within a week, and customers notice.',
    cat: 'catfood',
    icon: 'catfoodPremium',
    cost: 18,
    quality: 2,
    portions: 6,
    shelf: 22,
  },
  fresh_fish: {
    name: 'Fresh Fish',
    desc: "It was landed this morning. It makes for silky coats and delighted cats, but it doesn't keep for long.",
    cat: 'catfood',
    icon: 'fish',
    cost: 30,
    quality: 3,
    portions: 6,
    shelf: 3,
  },
  gourmet: {
    name: 'Gourmet Cans',
    desc: "It's absurd, but it works. The cats get visibly smug.",
    cat: 'catfood',
    icon: 'catfoodGourmet',
    cost: 44,
    quality: 4,
    portions: 6,
    shelf: 40,
    rare: true,
  },
  catnip: {
    name: 'Catnip',
    desc: 'One pinch turns the whole room into entertainment for an hour.',
    cat: 'supply',
    icon: 'catnip',
    cost: 22,
    shelf: 30,
  },
  treats: {
    name: 'Cat Treats',
    desc: "It's the universal apology.",
    cat: 'supply',
    icon: 'treats',
    cost: 14,
    shelf: 30,
  },
  medicine: {
    name: 'Cat Medicine',
    desc: 'It treats one sick cat at home, if you catch it early.',
    cat: 'supply',
    icon: 'medicine',
    cost: 46,
    shelf: 99,
  },
  vitamins: {
    name: 'Vitamins',
    desc: 'It makes illness less likely for a while. Apparently it tastes revolting.',
    cat: 'supply',
    icon: 'vitamins',
    cost: 34,
    shelf: 60,
  },
  brush: {
    name: 'Grooming Brush',
    desc: 'Use it to do a rough job yourself between trips to the groomer.',
    cat: 'supply',
    icon: 'brush',
    cost: 60,
    tool: true,
  },
  ribbon: {
    name: 'Ribbon Collar',
    desc: "It's purely decorative, and it's extremely effective.",
    cat: 'supply',
    icon: 'ribbon',
    cost: 40,
    wearable: true,
    appeal: 0.08,
  },
  bell: {
    name: 'Little Bell',
    desc: 'With a bell on, you always know where they are. So does everyone else.',
    cat: 'supply',
    icon: 'bell',
    cost: 55,
    wearable: true,
    appeal: 0.12,
  },
  toy_ball: {
    name: 'Bouncy Ball',
    desc: 'It ends up under the furniture within the hour. Put it down and the cats will find it.',
    cat: 'supply',
    icon: 'toyBall',
    cost: 28,
    place: 'toyBall',
    appeal: 0.2,
    catJoy: 0.8,
  },
  toy_yarn: {
    name: 'Ball of Yarn',
    desc: "It's a classic that has never been beaten. Set it out and see.",
    cat: 'supply',
    icon: 'toyYarn',
    cost: 24,
    place: 'toyYarn',
    appeal: 0.25,
    catJoy: 0.9,
  },
  toy_wand: {
    name: 'Feather Wand',
    desc: "Stand it in the room and customers can't resist picking it up. Neither can the cats, which is the point.",
    cat: 'supply',
    icon: 'toyWand',
    cost: 46,
    place: 'toyWand',
    appeal: 0.5,
    catJoy: 1.4,
    wand: true,
  },
  f_chair: {
    name: 'Wooden Chair',
    desc: "It's a place to sit, which is the foundation of hospitality.",
    cat: 'furniture',
    icon: 'chair',
    cost: 55,
    place: 'chair',
    seats: 1,
    appeal: 0.4,
  },
  f_stool: {
    name: 'Padded Stool',
    desc: "It has no back, but it's cheerful.",
    cat: 'furniture',
    icon: 'stool',
    cost: 70,
    place: 'stool',
    seats: 1,
    appeal: 0.5,
  },
  f_table: {
    name: 'Round Table',
    desc: 'It fits two comfortably, or three if they like each other.',
    cat: 'furniture',
    icon: 'table',
    cost: 110,
    place: 'tableRound',
    appeal: 0.6,
  },
  f_table_cloth: {
    name: 'Dressed Table',
    desc: 'The cloth suggests you have standards.',
    cat: 'furniture',
    icon: 'tableCloth',
    cost: 175,
    place: 'tableCloth',
    appeal: 1.1,
  },
  f_table_long: {
    name: 'Long Table',
    desc: "It's for groups, and groups order more.",
    cat: 'furniture',
    icon: 'tableLong',
    cost: 210,
    place: 'tableSq',
    appeal: 0.9,
  },
  f_sofa: {
    name: 'Velvet Couch',
    desc: "People stay far too long on this. That's the point.",
    cat: 'furniture',
    icon: 'sofa',
    cost: 420,
    place: 'sofa',
    seats: 3,
    appeal: 2.4,
  },
  f_plant: {
    name: 'Potted Fern',
    desc: 'It instantly makes a room look cared for.',
    cat: 'furniture',
    icon: 'plant',
    cost: 90,
    place: 'plantPot',
    appeal: 0.9,
  },
  f_lamp: {
    name: 'Floor Lamp',
    desc: 'It casts a warm pool of light, which is essential after dark.',
    cat: 'furniture',
    icon: 'floorlamp',
    cost: 130,
    place: 'lampIn',
    appeal: 1.1,
    light: true,
  },
  f_painting: {
    name: 'Landscape Painting',
    desc: "It's the valley, badly painted and dearly loved.",
    cat: 'furniture',
    icon: 'painting',
    cost: 160,
    place: 'painting',
    appeal: 1.2,
    wall: true,
  },
  f_bookshelf: {
    name: 'Bookshelf',
    desc: 'People browse, and browsing people order tea.',
    cat: 'furniture',
    icon: 'bookshelf',
    cost: 240,
    place: 'bookshelf',
    appeal: 1.6,
  },
  f_fireplace: {
    name: 'Stone Fireplace',
    desc: 'On a wet afternoon this pays for itself.',
    cat: 'furniture',
    icon: 'fireplace',
    cost: 680,
    place: 'fireplace',
    appeal: 3.2,
    light: true,
  },
  f_piano: {
    name: 'Upright Piano',
    desc: 'Somebody always knows a song or two.',
    cat: 'furniture',
    icon: 'piano',
    cost: 900,
    place: 'piano',
    appeal: 3.6,
    rare: true,
  },
  f_cattower: {
    name: 'Cat Tower',
    desc: 'The high shelf is the best seat in the house, and everyone knows it.',
    cat: 'furniture',
    icon: 'cattower',
    cost: 180,
    place: 'catTower',
    appeal: 1,
    catJoy: 2,
  },
  f_catbed: {
    name: 'Cat Bed',
    desc: "They'll sleep in the box it came in first. Eventually, they'll sleep in this.",
    cat: 'furniture',
    icon: 'catbed',
    cost: 85,
    place: 'catBed',
    appeal: 0.6,
    catJoy: 1.4,
  },
  f_scratch: {
    name: 'Scratching Post',
    desc: "It saves the couch, and it's worth every fish.",
    cat: 'furniture',
    icon: 'scratchpost',
    cost: 95,
    place: 'scratchPost',
    appeal: 0.3,
    catJoy: 1.6,
  },
  f_bowl: {
    name: 'Feeding Bowl',
    desc: 'More bowls means fewer arguments.',
    cat: 'furniture',
    icon: 'catbowl',
    cost: 35,
    place: 'catBowl',
    appeal: 0.1,
    catJoy: 0.6,
  },
  f_patio_chair: {
    name: 'Patio Chair',
    desc: "It's slatted, stackable, and surprisingly comfortable for what it is.",
    cat: 'furniture',
    icon: 'patioChair',
    cost: 65,
    place: 'patioChair',
    seats: 1,
    appeal: 0.45,
    outdoor: true,
  },
  f_patio_stool: {
    name: 'Patio Stool',
    desc: "It's light enough to move but heavy enough to stay put in a breeze.",
    cat: 'furniture',
    icon: 'patioStool',
    cost: 55,
    place: 'patioStool',
    seats: 1,
    appeal: 0.4,
    outdoor: true,
  },
  f_patio_table: {
    name: 'Patio Table',
    desc: "It has a mesh top, so rain goes straight through. That's the whole idea.",
    cat: 'furniture',
    icon: 'patioTable',
    cost: 130,
    place: 'patioTable',
    appeal: 0.7,
    outdoor: true,
  },
  f_patio_bench: {
    name: 'Garden Bench',
    desc: 'It seats three politely, two comfortably, or one gloriously.',
    cat: 'furniture',
    icon: 'patioBench',
    cost: 260,
    place: 'patioBench',
    seats: 3,
    appeal: 1.5,
    outdoor: true,
  },
  f_umbrella: {
    name: 'Umbrella Table',
    desc: 'It gives shade on hot days and shelter when the rain comes suddenly, so it earns its keep either way.',
    cat: 'furniture',
    icon: 'umbrella',
    cost: 340,
    place: 'umbrella',
    appeal: 2.2,
    outdoor: true,
  },
  f_fountain: {
    name: 'Stone Fountain',
    desc: "It's absurdly expensive. People sit near it and forget to leave, and the cats stare at it for hours.",
    cat: 'furniture',
    icon: 'fountain',
    cost: 1400,
    place: 'fountain',
    appeal: 4.2,
    rare: true,
    outdoor: true,
    catJoy: 1.2,
  },
  f_telephone: {
    name: 'Telephone',
    desc: "It's cream Bakelite with a dial and a bell loud enough to hear from the pantry. People call up wanting things brought to them.",
    cat: 'furniture',
    icon: 'phone',
    place: 'phone',
    appeal: 0.4,
  },
  f_counter: {
    name: 'Service Counter',
    desc: 'This is where the money happens.',
    cat: 'furniture',
    icon: 'counterUnit',
    cost: 260,
    place: 'counter',
    appeal: 0.5,
  },
  f_case: {
    name: 'Pastry Case',
    desc: 'Cake at eye level sells itself.',
    cat: 'furniture',
    icon: 'cake',
    cost: 320,
    place: 'pastryCase',
    appeal: 1.4,
  },
  f_machine: {
    name: 'Coffee Machine',
    desc: 'It hisses impressively, and customers trust a machine that hisses.',
    cat: 'furniture',
    icon: 'grinder',
    cost: 380,
    place: 'coffeeMachine',
    appeal: 1.2,
  },
  f_bar: {
    name: 'Bar Counter',
    desc: "It's three yards of polished oak. People who'd never take a table will happily perch at a bar.",
    cat: 'furniture',
    icon: 'bar',
    cost: 480,
    place: 'bar',
    appeal: 2.4,
  },
  f_barstool: {
    name: 'Bar Stool',
    desc: "It's tall and swivelly, and it's always taken by whoever got here first.",
    cat: 'furniture',
    icon: 'barstool',
    cost: 95,
    place: 'barStool',
    seats: 1,
    appeal: 0.7,
  },
  f_rug: {
    name: 'Woven Rug',
    desc: 'It softens the whole room, and the acoustics with it.',
    cat: 'furniture',
    icon: 'rug',
    cost: 140,
    place: 'rug',
    appeal: 1,
    floor: true,
  },
  pickaxe: {
    name: 'Rock Pick',
    desc: "It's heavy, and it splits rocks like cheese.",
    cat: 'key',
    icon: 'hammer',
    cost: 320,
  },
  shears: {
    name: 'Hedge Shears',
    desc: "They're for brambles that have gotten too big for their britches.",
    cat: 'key',
    icon: 'hammer',
    cost: 180,
  },
  rope: {
    name: 'Coil of Rope',
    desc: "It's twenty fathoms of good hemp.",
    cat: 'key',
    icon: 'bag',
    cost: 150,
  },
  valley_map: {
    name: 'Valley Map',
    desc: "It's hand-drawn and slightly wrong about the north, but it shows every village and every taxi perch, including the ones you haven't walked to yet.",
    cat: 'key',
    icon: 'map',
    cost: 240,
    reveals: true,
  },
  honey: {
    name: 'Jar of Honey',
    desc: "It's sunlight in a jar. If the baker sees it, honey bakes will be on the menu.",
    cat: 'key',
    icon: 'honey',
    cost: 55,
  },
  seashell: {
    name: 'Spiral Shell',
    desc: 'It holds the sound of the sea, or of your own blood, depending on who you ask.',
    cat: 'key',
    icon: 'shell',
  },
  wildflowers: {
    name: 'Wildflowers',
    desc: "You picked them from the meadow. They're wilting slightly, but they're still lovely.",
    cat: 'key',
    icon: 'bouquet',
  },
  lost_bell: {
    name: 'A Lost Bell',
    desc: "Someone's missing this. There's a name scratched on the inside.",
    cat: 'key',
    icon: 'bell',
  },
  golden_collar: {
    name: 'A Golden Collar',
    desc: "It's heavier than it looks, and still bright under two centuries of river mud. The engraving says SIR WOOFERS.",
    cat: 'key',
    icon: 'bell',
  },
  lantern: {
    name: 'Storm Lantern',
    desc: 'It burns steady in the wind. Things out at night are easier to see, and a little harder to ignore.',
    cat: 'key',
    icon: 'floorlamp',
    price: 90,
  },
  logbook: {
    name: "Keeper's Logbook",
    desc: 'It holds eleven years of weather and tides, and one line about a cat.',
    cat: 'key',
    icon: 'book',
  },
  letter: {
    name: 'A Letter',
    desc: "It's sealed and addressed, and it's waiting for a bird.",
    cat: 'key',
    icon: 'letter',
  },
  s: {
    name: 'Strawberry',
    desc: '',
    cat: 'food',
    icon: 'berry',
    glyph: 'parcel',
    colour: '#d0a659',
    cost: 3,
    price: 12,
    appeal: 1,
    shelf: 4,
    temp: 'cold',
  },
};
