// Everything you can carry, buy, cook or put down.
//
// Written by the editor in tools/editor. Everything in here is data: no
// functions, no imports, nothing that cannot survive a round trip through
// JSON. Hand edits are welcome and will be kept, but the formatting and any
// comments outside this header are replaced the next time the editor saves.
// A prose note about a particular entry belongs in its own `note` field,
// which is data and does survive.

export const ITEM_DATA = {
  house_coffee: {
    name: 'House Coffee',
    desc: 'Dependable. Nobody has ever complained about it, which is its own kind of praise.',
    cat: 'drink',
    icon: 'coffee',
    cost: 4,
    price: 12,
    appeal: 1,
    temp: 'hot',
    shelf: 8,
  },
  espresso: {
    name: 'Espresso',
    desc: 'Small, dark, and extremely serious.',
    cat: 'drink',
    icon: 'espresso',
    cost: 5,
    price: 16,
    appeal: 1.15,
    temp: 'hot',
    shelf: 8,
  },
  latte: {
    name: 'Latte',
    desc: 'The foam has a cat face on it. It takes you nine tries each time.',
    cat: 'drink',
    icon: 'latte',
    cost: 7,
    price: 21,
    appeal: 1.3,
    temp: 'hot',
    shelf: 4,
  },
  black_tea: {
    name: 'Black Tea',
    desc: 'Strong enough to stand a spoon in, if that is your preference.',
    cat: 'drink',
    icon: 'tea',
    cost: 3,
    price: 11,
    appeal: 1,
    temp: 'hot',
    shelf: 24,
  },
  herbal_tea: {
    name: 'Herbal Tea',
    desc: 'Chamomile, mostly. People fall asleep in the window seat.',
    cat: 'drink',
    icon: 'herbal',
    cost: 5,
    price: 17,
    appeal: 1.2,
    temp: 'hot',
    shelf: 24,
  },
  matcha: {
    name: 'Matcha',
    desc: 'Bright green and quietly expensive.',
    cat: 'drink',
    icon: 'matcha',
    cost: 9,
    price: 27,
    appeal: 1.5,
    temp: 'hot',
    shelf: 14,
  },
  cocoa: {
    name: 'Hot Cocoa',
    desc: 'Two marshmallows. Three if you like them.',
    cat: 'drink',
    icon: 'cocoa',
    cost: 6,
    price: 19,
    appeal: 1.3,
    temp: 'hot',
    shelf: 12,
  },
  lemonade: {
    name: 'Lemonade',
    desc: 'Made fresh, which is why it never lasts.',
    cat: 'drink',
    icon: 'lemonade',
    cost: 4,
    price: 14,
    appeal: 1.1,
    temp: 'cold',
    shelf: 4,
  },
  milk: {
    name: 'Warm Milk',
    desc: 'The cats become extremely interested whenever you pour it.',
    cat: 'drink',
    icon: 'milk',
    cost: 3,
    price: 9,
    appeal: 0.95,
    temp: 'hot',
    shelf: 3,
  },
  dandelion: {
    name: 'Dandelion Cordial',
    desc: 'Made from a weed by somebody who knows exactly which weed. Tastes like a field in June.',
    cat: 'drink',
    icon: 'dandelion',
    cost: 6,
    price: 19,
    appeal: 1.35,
    temp: 'cold',
    shelf: 14,
  },
  iced_coffee: {
    name: 'Iced Coffee',
    desc: 'Over a lot of ice, in a tall glass, on the one week a year it is warranted.',
    cat: 'drink',
    icon: 'icedCoffee',
    cost: 5,
    price: 17,
    appeal: 1.2,
    temp: 'cold',
    shelf: 3,
  },
  iced_tea: {
    name: 'Iced Tea',
    desc: 'With a slice of lemon balanced on the rim, which nobody eats.',
    cat: 'drink',
    icon: 'icedTea',
    cost: 4,
    price: 15,
    appeal: 1.15,
    temp: 'cold',
    shelf: 3,
  },
  cider: {
    name: 'Cloudy Cider',
    desc: 'Pressed from the orchard up the valley. Very cloudy. Very good.',
    cat: 'drink',
    icon: 'cider',
    cost: 8,
    price: 24,
    appeal: 1.4,
    temp: 'cold',
    shelf: 20,
  },
  smoked_tea: {
    name: 'Smoked Lapsang',
    desc: 'Tastes like a bonfire in the best possible way. Divisive. Profitable.',
    cat: 'drink',
    icon: 'tea',
    cost: 14,
    price: 42,
    appeal: 1.95,
    temp: 'hot',
    shelf: 24,
    rare: true,
  },
  cookie: {
    name: 'Butter Cookie',
    desc: 'Shaped like a paw. Badly, but sincerely.',
    cat: 'food',
    icon: 'cookie',
    cost: 3,
    price: 10,
    appeal: 1,
    shelf: 10,
  },
  scone: {
    name: 'Scone',
    desc: 'Jam first. This is not negotiable in this valley.',
    cat: 'food',
    icon: 'scone',
    cost: 5,
    price: 16,
    appeal: 1.2,
    shelf: 3,
  },
  croissant: {
    name: 'Croissant',
    desc: 'Leaves flakes everywhere. The cats consider this a feature.',
    cat: 'food',
    icon: 'croissant',
    cost: 6,
    price: 18,
    appeal: 1.3,
    shelf: 2,
  },
  muffin: {
    name: 'Berry Muffin',
    desc: 'Berries from the hedgerow, mostly picked by you.',
    cat: 'food',
    icon: 'muffin',
    cost: 5,
    price: 15,
    appeal: 1.15,
    shelf: 3,
  },
  sandwich: {
    name: 'Sandwich',
    desc: 'Cut into triangles, because squares are for weekdays.',
    cat: 'food',
    icon: 'sandwich',
    cost: 7,
    price: 20,
    appeal: 1.2,
    shelf: 2,
  },
  toast: {
    name: 'Honey Toast',
    desc: 'Thick cut, dripping. Deeply unserious food.',
    cat: 'food',
    icon: 'toast',
    cost: 6,
    price: 19,
    appeal: 1.3,
    temp: 'hot',
    shelf: 2,
  },
  cake: {
    name: 'Sponge Cake',
    desc: 'A slice big enough to justify a second visit.',
    cat: 'food',
    icon: 'cake',
    cost: 9,
    price: 28,
    appeal: 1.55,
    shelf: 3,
  },
  pancakes: {
    name: 'Pancake Stack',
    desc: 'Weekend food. People come specifically.',
    cat: 'food',
    icon: 'pancakes',
    cost: 8,
    price: 25,
    appeal: 1.45,
    temp: 'hot',
    shelf: 1,
  },
  parfait: {
    name: 'Berry Parfait',
    desc: 'Layered in a tall glass so it looks like it took effort.',
    cat: 'food',
    icon: 'parfait',
    cost: 11,
    price: 32,
    appeal: 1.65,
    temp: 'cold',
    shelf: 2,
  },
  pie: {
    name: 'Fruit Pie',
    desc: 'Whole pie, sold by the slice, gone by three.',
    cat: 'food',
    icon: 'pie',
    cost: 12,
    price: 36,
    appeal: 1.75,
    temp: 'hot',
    shelf: 4,
  },
  honey_scone: {
    name: 'Honey Scone',
    desc: "Clover's honey, warm from the oven. People have written letters about this.",
    cat: 'food',
    icon: 'scone',
    cost: 8,
    price: 26,
    appeal: 1.6,
    temp: 'hot',
    shelf: 3,
    rare: true,
  },
  ice_cream: {
    name: 'Ice Cream',
    desc: 'Two scoops. Melts faster than anybody plans for.',
    cat: 'food',
    icon: 'iceCream',
    cost: 6,
    price: 20,
    appeal: 1.35,
    temp: 'cold',
    shelf: 2,
  },
  fishcake: {
    name: 'Fishcake',
    desc: 'Every cat in the building will supervise you making these.',
    cat: 'food',
    icon: 'fishcake',
    cost: 10,
    price: 30,
    appeal: 1.5,
    temp: 'hot',
    shelf: 2,
  },
  kibble: {
    name: 'Everyday Kibble',
    desc: 'Keeps a cat alive and mildly disappointed.',
    cat: 'catfood',
    icon: 'catfood',
    cost: 8,
    quality: 1,
    portions: 6,
    shelf: 30,
  },
  good_food: {
    name: 'Good Cat Food',
    desc: 'Coats get glossier within the week. Customers notice.',
    cat: 'catfood',
    icon: 'catfoodPremium',
    cost: 18,
    quality: 2,
    portions: 6,
    shelf: 22,
  },
  fresh_fish: {
    name: 'Fresh Fish',
    desc: 'Landed this morning. Silky coats, delighted cats, very short shelf life.',
    cat: 'catfood',
    icon: 'fish',
    cost: 30,
    quality: 3,
    portions: 6,
    shelf: 3,
  },
  gourmet: {
    name: 'Gourmet Tins',
    desc: 'Absurd. Effective. The cats become visibly smug.',
    cat: 'catfood',
    icon: 'catfoodGourmet',
    cost: 44,
    quality: 4,
    portions: 6,
    shelf: 40,
    rare: true,
  },
  catnip: {
    name: 'Catnip',
    desc: 'One pinch and the whole room becomes entertainment for an hour.',
    cat: 'supply',
    icon: 'catnip',
    cost: 22,
    shelf: 30,
  },
  treats: {
    name: 'Cat Treats',
    desc: 'The universal apology.',
    cat: 'supply',
    icon: 'treats',
    cost: 14,
    shelf: 30,
  },
  medicine: {
    name: 'Cat Medicine',
    desc: 'Treats one sick cat at home, if you catch it early.',
    cat: 'supply',
    icon: 'medicine',
    cost: 46,
    shelf: 99,
  },
  vitamins: {
    name: 'Vitamins',
    desc: 'Makes illness less likely for a while. Tastes revolting, apparently.',
    cat: 'supply',
    icon: 'vitamins',
    cost: 34,
    shelf: 60,
  },
  brush: {
    name: 'Grooming Brush',
    desc: 'Do a rough job yourself between proper groomings.',
    cat: 'supply',
    icon: 'brush',
    cost: 60,
    tool: true,
  },
  ribbon: {
    name: 'Ribbon Collar',
    desc: 'Purely decorative. Extremely effective.',
    cat: 'supply',
    icon: 'ribbon',
    cost: 40,
    wearable: true,
    appeal: 0.08,
  },
  bell: {
    name: 'Little Bell',
    desc: 'You always know where they are. So does everyone else.',
    cat: 'supply',
    icon: 'bell',
    cost: 55,
    wearable: true,
    appeal: 0.12,
  },
  toy_ball: {
    name: 'Bouncy Ball',
    desc: 'Ends up under the furniture within the hour. Put it down and the cats will find it.',
    cat: 'supply',
    icon: 'toyBall',
    cost: 28,
    place: 'toyBall',
    appeal: 0.2,
    catJoy: 0.8,
  },
  toy_yarn: {
    name: 'Ball of Yarn',
    desc: 'Classic. Undefeated. Set it out and see.',
    cat: 'supply',
    icon: 'toyYarn',
    cost: 24,
    place: 'toyYarn',
    appeal: 0.25,
    catJoy: 0.9,
  },
  toy_wand: {
    name: 'Feather Wand',
    desc: 'Stand it in the room and customers cannot resist picking it up. Neither can the cats, which is the point.',
    cat: 'supply',
    icon: 'toyWand',
    cost: 46,
    place: 'toyWand',
    appeal: 0.5,
    catJoy: 1.4,
    wand: true,
  },
  f_chair: {
    name: 'Wooden Chair',
    desc: 'A place to sit. The foundation of hospitality.',
    cat: 'furniture',
    icon: 'chair',
    cost: 55,
    place: 'chair',
    seats: 1,
    appeal: 0.4,
  },
  f_stool: {
    name: 'Padded Stool',
    desc: 'No back, but cheerful.',
    cat: 'furniture',
    icon: 'stool',
    cost: 70,
    place: 'stool',
    seats: 1,
    appeal: 0.5,
  },
  f_table: {
    name: 'Round Table',
    desc: 'Fits two comfortably, three if they like each other.',
    cat: 'furniture',
    icon: 'table',
    cost: 110,
    place: 'tableRound',
    appeal: 0.6,
  },
  f_table_cloth: {
    name: 'Dressed Table',
    desc: 'The cloth suggests you have standards.',
    cat: 'furniture',
    icon: 'tableCloth',
    cost: 175,
    place: 'tableCloth',
    appeal: 1.1,
  },
  f_table_long: {
    name: 'Long Table',
    desc: 'For groups. Groups order more.',
    cat: 'furniture',
    icon: 'tableLong',
    cost: 210,
    place: 'tableSq',
    appeal: 0.9,
  },
  f_sofa: {
    name: 'Velvet Sofa',
    desc: 'People stay far too long on this. That is the point.',
    cat: 'furniture',
    icon: 'sofa',
    cost: 420,
    place: 'sofa',
    seats: 3,
    appeal: 2.4,
  },
  f_plant: {
    name: 'Potted Fern',
    desc: 'Instantly makes a room look cared for.',
    cat: 'furniture',
    icon: 'plant',
    cost: 90,
    place: 'plantPot',
    appeal: 0.9,
  },
  f_lamp: {
    name: 'Floor Lamp',
    desc: 'Warm pool of light. Essential after dark.',
    cat: 'furniture',
    icon: 'floorlamp',
    cost: 130,
    place: 'lampIn',
    appeal: 1.1,
    light: true,
  },
  f_painting: {
    name: 'Landscape Painting',
    desc: 'The valley, badly painted, beloved.',
    cat: 'furniture',
    icon: 'painting',
    cost: 160,
    place: 'painting',
    appeal: 1.2,
    wall: true,
  },
  f_bookshelf: {
    name: 'Bookshelf',
    desc: 'People browse. Browsing people order tea.',
    cat: 'furniture',
    icon: 'bookshelf',
    cost: 240,
    place: 'bookshelf',
    appeal: 1.6,
  },
  f_fireplace: {
    name: 'Stone Fireplace',
    desc: 'On a wet afternoon this pays for itself.',
    cat: 'furniture',
    icon: 'fireplace',
    cost: 680,
    place: 'fireplace',
    appeal: 3.2,
    light: true,
  },
  f_piano: {
    name: 'Upright Piano',
    desc: 'Somebody always knows three songs.',
    cat: 'furniture',
    icon: 'piano',
    cost: 900,
    place: 'piano',
    appeal: 3.6,
    rare: true,
  },
  f_cattower: {
    name: 'Cat Tower',
    desc: 'The high shelf is the best seat in the house, and everyone knows it.',
    cat: 'furniture',
    icon: 'cattower',
    cost: 180,
    place: 'catTower',
    appeal: 1,
    catJoy: 2,
  },
  f_catbed: {
    name: 'Cat Bed',
    desc: 'They will sleep in the box it came in. Then, eventually, in this.',
    cat: 'furniture',
    icon: 'catbed',
    cost: 85,
    place: 'catBed',
    appeal: 0.6,
    catJoy: 1.4,
  },
  f_scratch: {
    name: 'Scratching Post',
    desc: 'Saves the sofa. Worth every fish.',
    cat: 'furniture',
    icon: 'scratchpost',
    cost: 95,
    place: 'scratchPost',
    appeal: 0.3,
    catJoy: 1.6,
  },
  f_bowl: {
    name: 'Feeding Bowl',
    desc: 'More bowls, fewer arguments.',
    cat: 'furniture',
    icon: 'catbowl',
    cost: 35,
    place: 'catBowl',
    appeal: 0.1,
    catJoy: 0.6,
  },
  f_patio_chair: {
    name: 'Patio Chair',
    desc: 'Slatted, stackable, and surprisingly comfortable for what it is.',
    cat: 'furniture',
    icon: 'patioChair',
    cost: 65,
    place: 'patioChair',
    seats: 1,
    appeal: 0.45,
    outdoor: true,
  },
  f_patio_stool: {
    name: 'Patio Stool',
    desc: 'Light enough to move, heavy enough to stay put in a breeze.',
    cat: 'furniture',
    icon: 'patioStool',
    cost: 55,
    place: 'patioStool',
    seats: 1,
    appeal: 0.4,
    outdoor: true,
  },
  f_patio_table: {
    name: 'Patio Table',
    desc: 'Mesh top. Rain goes straight through, which is the entire idea.',
    cat: 'furniture',
    icon: 'patioTable',
    cost: 130,
    place: 'patioTable',
    appeal: 0.7,
    outdoor: true,
  },
  f_patio_bench: {
    name: 'Garden Bench',
    desc: 'Seats three politely, two comfortably, one gloriously.',
    cat: 'furniture',
    icon: 'patioBench',
    cost: 260,
    place: 'patioBench',
    seats: 3,
    appeal: 1.5,
    outdoor: true,
  },
  f_umbrella: {
    name: 'Umbrella Table',
    desc: 'Shade on the hot days, shelter on the sudden ones. Earns its keep either way.',
    cat: 'furniture',
    icon: 'umbrella',
    cost: 340,
    place: 'umbrella',
    appeal: 2.2,
    outdoor: true,
  },
  f_fountain: {
    name: 'Stone Fountain',
    desc: 'Absurdly expensive. People sit near it and forget to leave, and the cats stare at it for hours.',
    cat: 'furniture',
    icon: 'fountain',
    cost: 1400,
    place: 'fountain',
    appeal: 4.2,
    rare: true,
    outdoor: true,
    catJoy: 1.2,
  },
  f_telephone: {
    name: 'Telephone',
    desc: 'Cream bakelite, a dial, and a bell loud enough to be heard from the pantry. People ring up wanting things brought to them.',
    cat: 'furniture',
    icon: 'phone',
    place: 'phone',
    appeal: 0.4,
  },
  f_counter: {
    name: 'Service Counter',
    desc: 'Where the money happens.',
    cat: 'furniture',
    icon: 'counterUnit',
    cost: 260,
    place: 'counter',
    appeal: 0.5,
  },
  f_case: {
    name: 'Pastry Case',
    desc: 'Cake at eye level sells itself.',
    cat: 'furniture',
    icon: 'cake',
    cost: 320,
    place: 'pastryCase',
    appeal: 1.4,
  },
  f_machine: {
    name: 'Coffee Machine',
    desc: 'Hisses impressively. Customers trust a machine that hisses.',
    cat: 'furniture',
    icon: 'grinder',
    cost: 380,
    place: 'coffeeMachine',
    appeal: 1.2,
  },
  f_bar: {
    name: 'Bar Counter',
    desc: 'Three yards of polished oak. People perch at a bar who would never take a table.',
    cat: 'furniture',
    icon: 'bar',
    cost: 480,
    place: 'bar',
    appeal: 2.4,
  },
  f_barstool: {
    name: 'Bar Stool',
    desc: 'Tall, swivelly, and always taken by whoever got here first.',
    cat: 'furniture',
    icon: 'barstool',
    cost: 95,
    place: 'barStool',
    seats: 1,
    appeal: 0.7,
  },
  f_rug: {
    name: 'Woven Rug',
    desc: 'Softens the whole room, and the acoustics with it.',
    cat: 'furniture',
    icon: 'rug',
    cost: 140,
    place: 'rug',
    appeal: 1,
    floor: true,
  },
  pickaxe: {
    name: 'Chalk Pick',
    desc: 'Heavy. Splits chalk like cheese.',
    cat: 'key',
    icon: 'hammer',
    cost: 320,
  },
  shears: {
    name: 'Hedge Shears',
    desc: 'For brambles that have got ideas above their station.',
    cat: 'key',
    icon: 'hammer',
    cost: 180,
  },
  rope: {
    name: 'Coil of Rope',
    desc: 'Twenty fathoms of good hemp.',
    cat: 'key',
    icon: 'bag',
    cost: 150,
  },
  valley_map: {
    name: 'Valley Map',
    desc: 'Hand-drawn, slightly wrong about the north, but it shows every village and every taxi perch — including the ones you have not walked to yet.',
    cat: 'key',
    icon: 'map',
    cost: 240,
    reveals: true,
  },
  honey: {
    name: 'Jar of Honey',
    desc: 'Sunlight in a jar. Unlocks honey bakes if the baker sees it.',
    cat: 'key',
    icon: 'honey',
    cost: 55,
  },
  seashell: {
    name: 'Spiral Shell',
    desc: 'Holds the sound of the sea, or of your own blood, depending who you ask.',
    cat: 'key',
    icon: 'shell',
  },
  wildflowers: {
    name: 'Wildflowers',
    desc: 'Picked from the meadow. Wilting slightly, still lovely.',
    cat: 'key',
    icon: 'bouquet',
  },
  lost_bell: {
    name: 'A Lost Bell',
    desc: 'Someone is missing this. It has a name scratched on the inside.',
    cat: 'key',
    icon: 'bell',
  },
  golden_collar: {
    name: 'A Golden Collar',
    desc: 'Heavier than it looks, and still bright under two centuries of river mud. Engraved: SIR WOOFERS.',
    cat: 'key',
    icon: 'bell',
  },
  lantern: {
    name: 'Storm Lantern',
    desc: 'Burns steady in wind. Things out at night are easier to see, and slightly less easy to ignore.',
    cat: 'key',
    icon: 'floorlamp',
    price: 90,
  },
  logbook: {
    name: "Keeper's Logbook",
    desc: 'Eleven years of weather, tides, and one line about a cat.',
    cat: 'key',
    icon: 'book',
  },
  letter: {
    name: 'A Letter',
    desc: 'Sealed, addressed, and waiting for a bird.',
    cat: 'key',
    icon: 'letter',
  },
};
