// The quests, as plain data.
//
// Written by the editor in tools/editor. Everything in here is data: no
// functions, no imports, nothing that cannot survive a round trip through
// JSON. Hand edits are welcome and will be kept, but the formatting and any
// comments outside this header are replaced the next time the editor saves.
// A prose note about a particular entry belongs in its own `note` field,
// which is data and does survive.

export const QUESTS = [
  {
    id: 'first_beans',
    title: 'Something To Sell',
    giver: 'pip',
    desc: 'Pip thinks you should stock up on coffee and something sweet before you open for real.',
    objective: { type: 'stock', any: ['house_coffee', 'black_tea'], count: 10 },
    progress: 'Stock ten portions of coffee or tea. You can buy them from the grocer in Brambleford.',
    reward: {
      items: [['cookie', 12]],
      journal: 'Pip was good friends with your grandmother, close enough that she gave him her cookie recipe. He gave you a dozen of those cookies to help get your cat cafe off the ground.',
      rep: 0.5,
      friendship: ['pip'],
    },
    offer: "You've opened a cafe, so you're going to need something to sell.\n\nIf you buy ten portions of coffee or tea, I'll throw in some cookies for free.",
    complete: "Oh, I see you're taking me up on my offer. Here, take these cookies. They're made from your grandmother's recipe.\n\nI think of her kindness every time I bake them. I sell them to other grocers all over the valley.\n\nYour grandmother helped me get my business started. I hope someday you'll get to help someone else start theirs.",
  },
  {
    id: 'honey_run',
    title: 'A Jar of Sunlight',
    giver: 'dough',
    desc: "Dough wants a jar of Clover's honey from Oakhollow for a scone recipe.",
    objective: { type: 'item', item: 'honey', count: 1 },
    progress: 'Buy a jar of honey from the beekeeper in Oakhollow.',
    reward: {
      money: 140,
      flags: ['recipe_honey'],
      items: [['honey_scone', 12]],
      journal: "After you brought Dough a jar of honey, they started selling honey scones again, and everyone in the valley rejoiced. At least, you assume they rejoiced. Nobody actually said so.",
      friendship: ['dough'],
    },
    offer: "Clover keeps bees out in Oakhollow, east through the woods.\n\nIf you bring me a jar of her honey, I'll make honey scones. People will flock to your cafe for them.",
    complete: "That's exactly what I needed! Here are your honey scones, as promised.",
  },
  {
    id: 'lost_bell',
    title: 'The Lost Bell',
    giver: 'marigold',
    desc: 'Marigold found a little bell on the road with a name scratched inside it, and thinks it belongs to someone in Saltmere.',
    objective: { type: 'deliver', item: 'lost_bell', to: 'shrimp' },
    progress: "Take the bell to Shrimp in Saltmere, on the coast to the southwest. He's the otter by the water.",
    reward: {
      money: 180,
      friendship: ['shrimp', 'marigold'],
      items: [['bell', 1]],
      journal: 'Marigold found a bell with a name scratched inside. You returned it to its owner, Shrimp in Saltmere. Now you have two new friends to send letters to!',
      rep: 0.5,
    },
    offer: 'Somebody named Shrimp lost a bell. How do I know? I found a bell with "Shrimp" scratched inside it, and Shrimp sounds like a Saltmere name to me.\n\nCould you take it down south to Saltmere, on the coast, and ask around?',
    complete: "Thank you for bringing my bell back!\n\nI heard you run a cat cafe. I guess you find lost bells on the side, too? Thanks again!",
  },
  {
    id: 'flower_delivery',
    title: 'Flowers for Somebody',
    giver: 'nettle',
    desc: 'Nettle picked wildflowers for someone in Hollowdown but is too shy to deliver them.',
    objective: { type: 'deliver', item: 'wildflowers', to: 'chalk' },
    progress: 'Take the flowers to Chalk in Hollowdown, up in the chalk hills to the north.',
    reward: {
      money: 900,
      friendship: ['chalk', 'nettle'],
      flags: ['hint_taxi'],
      journal: "You delivered a bouquet of handpicked wildflowers to Chalk for Nettle. Chalk tipped you off that the taxi birds will fly you anywhere you've already been. There's a perch in every town, and they fly from seven in the morning to seven at night.",
    },
    offer: "So... this is, um, a little embarrassing. I picked these flowers for someone up in Hollowdown, but now I can't bring myself to hand them over.\n\nWould you take them for me? They're for Chalk, the cute squirrel. You'll know who I mean.",
    complete: "Oh! Oh my, they're from Nettle? Golly gosh, that's so sweet. *blushes*\n\nHere's a tip for you: did you know the birds run a taxi service? There's a perch in every town. Here's enough money for a few rides.",
  },
  {
    id: 'sea_shell',
    title: 'Something for the Window',
    giver: 'juniper',
    note: "The quest is to ask around in Saltmere until you find someone who has a shell (it's Moth)",
    desc: 'Juniper thinks your cafe needs a spiral shell on the windowsill.',
    steps: [
      {
        note: 'Ask around in Saltmere for a spiral seashell.',
        objective: { type: 'talk', to: 'anchor' },
        progress: "Someone in Saltmere must have a spiral seashell lying around. They live right on the beach, for goodness' sake, so they probably have shells lining their gardens.",
        done: "A spiral shell? Sure, I've got one lying around. Here, you can have it.",
        gives: [['seashell', 1]],
        sets: ['seashell_acquired'],
      },
      {
        note: 'I showed the spiral seashell to Juniper and they took it for themselves and gave me a potted plant instead.',
        objective: { type: 'deliver', give: false, item: 'seashell', to: 'juniper' },
        progressWhen: [],
        done: "Trust me, a potted plant will do more for your cafe's atmosphere than this smelly shell.",
      },
    ],
    reward: {
      money: 0,
      items: [['f_plant', 2]],
      rep: 0.5,
      friendship: ['juniper', 'anchor'],
    },
    offer: "Your place needs something special, something with a story behind it.\n\nI know: a big spiral shell! There's got to be one down in Saltmere. I'd ask around instead of searching the beach, though, because that beach has been picked clean since before I was born.",
    complete: "Oh, it's perfect. Absolutely perfect!\n\nIn return, have these potted plants. They'll look nice in your cafe.",
  },
  {
    id: 'clear_the_path',
    title: 'The Fallen Rock',
    giver: 'brook',
    desc: 'A slab of rock is blocking the river bridge on the road east. Brook says the right tool could break it up.',
    objective: { type: 'flag', flag: 'barrier_eastpass' },
    progress: "Buy a rock pick at the Chalk Pit Store in Hollowdown, then follow the road due east out of town to the river. You can't miss the bridge, or the rock sitting on it.",
    reward: { money: 600, rep: 0.5, friendship: ['brook'] },
    offer: "The river's high after all that rain, and it washed out the bank under a chalk cliff east of here. A huge chunk of rock came down right across the middle of the bridge, and the water's deep on both sides.\n\nThat bridge was the road to Thistlewick. You can still get there the long way around, through Hollowdown and Oakhollow, but that's almost an hour nobody should have to walk twice.\n\nGet a rock pick from the Chalk Pit Store up in Hollowdown, and break up that rock. Everyone in town will be quietly grateful, even if not one of them says so.",
    complete: "You broke up that rock all by yourself?\n\nThat's great! The bridge is open again, so nobody has to go all the way around through Hollowdown to get to Thistlewick anymore.\n\nTake this money, and don't argue with me about it.",
  },
  {
    id: 'bramble_path',
    title: 'The Way to the Mill',
    giver: 'grist',
    desc: 'Brambles have swallowed the path to the old mill. Grist wants it cleared.',
    objective: { type: 'flag', flag: 'barrier_millpath' },
    progress: 'Buy hedge shears at the Chalk Pit Store in Hollowdown, then go to the little bridge on the mill path, northeast of here.',
    reward: { money: 380, items: [['valley_map', 1]] },
    offer: "The old mill technically belongs to my family, but I can't get to it. Brambles have taken over the whole bridge, and they've grown right across it, thick as rope.\n\nA pair of shears would do the trick. The hardware store up in Hollowdown sells them.",
    complete: "You got through! And you didn't fall through the floor, either, so that's two good things.\n\nHere's a map of the valley. It's wrong about the north, but it's better than nothing.",
  },
  {
    id: 'four_cats',
    title: 'A Proper Cattery',
    giver: 'thimble',
    desc: 'Thimble counts your cats at every chance, and thinks you need more of them.',
    objective: { type: 'cats', count: 4 },
    progress: 'Adopt four cats. Whisker & Paw, down the street, sells them.',
    reward: { money: 200, rep: 0.06 },
    offer: "I count your cats whenever I walk by, and you can never have too many.\n\nIf you get up to four cats, I'll give you something for your trouble.",
    complete: 'Oh! You have four cats now!\n\nHere, spend this on something nice for them.',
  },
  {
    id: 'good_coat',
    title: 'Show Me a Silky Coat',
    giver: 'suds',
    desc: 'Suds wants to show you that good food matters as much as grooming.',
    objective: { type: 'coat', quality: 1.12 },
    progress: "Feed a cat fresh fish or gourmet cans for a few days in a row. Kibble and regular cat food won't do it.",
    reward: {
      money: 240,
      items: [['brush', 1]],
      flags: ['hint_fish'],
      journal: 'Kelp brings in fresh fish in Saltmere every morning and sells out by noon. A cat that eats it gets a glossy coat in under a week.',
    },
    offer: "Everyone thinks grooming is the whole story, but it isn't. Food is half of it.\n\nFeed your cats fish or the gourmet cans for a few days (the cheap stuff won't make a difference), then bring one back to show me.",
    complete: "*Now* look at that! That's what I'm talking about.\n\nRemember to brush them between visits. And go see Kelp in Saltmere about fish, but make sure you get there before noon.",
  },
  {
    id: 'first_extension',
    title: 'Room to Breathe',
    giver: 'trowel',
    desc: "Trowel will believe you're serious once you've actually built something.",
    objective: { type: 'rooms', count: 2 },
    progress: 'Hire workers from me, then build one more room onto the cafe.',
    reward: { money: 300, rep: 0.08 },
    offer: "Everyone talks about renovating, but almost nobody actually does it.\n\nHire a crew, buy the materials, and add a room to your place. Then come back, and we'll talk about the real work.",
    complete: "You did it, and it's not bad at all.\n\nNow you're a real customer. Next time, we'll do something ambitious.",
  },
  {
    id: 'busy_day',
    title: 'A Day Worth Having',
    giver: 'ledger',
    desc: 'Ledger wants to see you make a really good profit in a single day.',
    objective: { type: 'profit', amount: 400 },
    progress: 'Make four hundred in profit in a single day, after all your costs.',
    reward: { money: 350, rep: 0.1 },
    offer: "Advice is cheap, but results aren't.\n\nMake four hundred in profit in one day, after wages, cat food, and everything else. Then I'll take you seriously.",
    complete: "You made four hundred in profit in a single day!\n\nYou've got a real business now. Congratulations, but don't get too comfortable.",
  },
  {
    id: 'rare_cat',
    title: 'A Cat of Distinction',
    giver: 'sable',
    desc: "Sable won't take you seriously until you own a rare breed.",
    objective: { type: 'rarecat' },
    progress: "Adopt a rare breed. I sell them here, on the days I'm open.",
    reward: { money: 400, items: [['ribbon', 2]], rep: 0.08 },
    offer: "Common cats are lovely, and I've got nothing against them.\n\nBut if you bring a rare breed into that room, watch what happens to your profits. Come back when you have one of mine.",
    complete: 'There, now your cafe has a *centerpiece*.\n\nTake these ribbons, too. Presentation is half the battle.',
  },
  {
    id: 'lighthouse_log',
    title: 'The Keeper Who Left',
    giver: 'slate',
    desc: "Slate wants to know what's in the lighthouse logbook.",
    objective: { type: 'item', item: 'logbook', count: 1 },
    progress: "Search the keeper's table in the lighthouse, west along the coast past Saltmere.",
    reward: { money: 300, items: [['lantern', 1]], rep: 0.05 },
    offer: "The lamp at Gullrock Lighthouse is still burning, but there's no keeper anymore, and nobody's brave enough to go look.\n\nThere's a logbook in there. If you bring it to me, I'll make it worth the walk.",
    complete: "It's eleven years of tides and weather... and then there's one line, near the end:\n\n'The cat has stopped coming. I shall wait a while longer.'\n\nHm. Take this lantern. Somebody should keep a light burning.",
  },
  {
    id: 'lane_end_hedge',
    title: 'The Mystery in the Hedge',
    giver: 'button',
    desc: 'Something moves in the hedge outside Button\'s house at night, and Button wants to know what it is.',
    steps: [
      {
        note: 'Look at the hedge at the end of the lane, after dark',
        objective: { type: 'flag', flag: 'saw_the_hedge' },
        progress: "Go look at the hedge after dark. Nothing happens during the day. Believe me, I've stood there and checked over and over.",
        done: "You SAW it? Ha! HA! So I'm not crazy after all. So... what do we do about it?",
      },
      {
        note: 'Speak to whatever is in the hedge',
        objective: { type: 'talk', to: 'woofers' },
        progress: "Go back to the hedge after dark and talk to whatever's in it. I'm too scared, so you'll have to do it without me!",
        done: "*the shape in the hedge lifts its head*\n\nYou can see me? Nobody has been able to see me in a very long time.\n\nI lost my collar. It was gold, with my name on it, and I've been searching this hedge for it for... a while. I can't remember where I had it last.\n\nI can't remember much at all, but I'm pretty sure I was IMPORTANT ENOUGH TO BE IN A HISTORY BOOK. MAYBE THE KIND OF BOOK THEY'D KEEP IN A LIBRARY?!",
      },
      {
        note: 'Read about Sir Woofers at the Reading Room in Brambleford',
        objective: { type: 'flag', flag: 'read_town_history' },
        progress: 'Read the town history at the Reading Room in Brambleford. Someone must have written about a famous dog dying, because someone writes everything down.',
        done: 'Sir Woofers wore the collar to the opening of Saltsouth Pier in 1800, and he never came home with it.\n\nAccording to a note in the margin, Saltsouth is the old name for Saltmere.',
      },
      {
        note: 'Search the mud at the end of Saltmere Pier',
        objective: { type: 'item', item: 'golden_collar', count: 1 },
        progress: 'Go to the end of the pier in Saltmere and search the mud down there.',
        done: "It's been in the mud for two hundred years, and it's still shiny.",
      },
      {
        note: 'Take the collar back to Sir Woofers, after dark',
        objective: {
          type: 'deliver',
          item: 'golden_collar',
          to: 'woofers',
          give: false,
        },
        progress: 'Take the collar back to the hedge after dark.',
        done: 'Now that I have my golden collar back, my soul can rest.\n\nThis collar brings back such happy memories. Thank you.',
      },
    ],
    reward: {
      money: 400,
      rep: 1,
      friendship: ['button'],
      items: [['catnip', 5]],
      journal: "Sir Woofers' soul can rest now that he has his golden collar back.",
    },
    offer: "Yes, I'm a corgi: short legs and tall tales. And I've got a tall tale for you... or is it?\n\nJust listen. The hedge in front of my house MOVES at night. It's not the wind, either. Just one part of it shakes, like there's a puppy in there sniffing around for a snack.\n\nI've barked at it until I couldn't bark anymore, and it doesn't seem to care, which is frankly insulting. You have cats, so you're used to nonsense. Would you go take a look?",
    complete: "Oh. Oh, that IS mine. That's my collar!\n\n*the very old dog stands still for the first time in two hundred years*\n\nThey put my name on it for the opening, you know. There was a ribbon and everything.\n\nThank you. Thank you so much. I'll stop bothering the hedge now.",
  },
  {
    id: 'moth_count',
    title: 'Fourteen Species',
    giver: 'moth',
    desc: "Moth counts moths, but there isn't enough light to count them by.",
    night: true,
    requires: 'heard_hint_shrimp',
    steps: [
      {
        note: 'Buy a storm lantern at the Chalk Pit Store in Hollowdown',
        objective: { type: 'item', item: 'lantern', count: 1 },
        progress: 'Buy a storm lantern at the Chalk Pit Store in Hollowdown. Ask for a storm lantern, not a fancy one.',
        done: "That's the one! Now bring it to Moth after dark.",
      },
      {
        note: 'Take the lantern to Moth, after dark',
        objective: { type: 'deliver', item: 'lantern', to: 'moth', give: false },
      },
    ],
    reward: {
      money: 150,
      items: [['seashell', 1]],
      friendship: ['moth'],
      rep: 0.1,
      journal: 'Moth counts moths at night. So when does he sleep? Anyway, you got him better light for his nighttime hobby, and he gave you a spiral seashell as thanks.',
    },
    offer: "You're up late. Good, because nobody else is ever awake this late.\n\nI count the moths on the lamps, you see. But the lamps in this town are terrible, and half of them are out.\n\nI'm pretty sure I've counted the same moth eleven times because of the bad lighting.\n\nYou can get a good storm lantern at the hardware store up in Hollowdown. Bring me one, and I'll show you something.",
    complete: "*Moth holds up the lantern, and the air fills with fluttering wings as moths crowd around it*\n\nFourteen! That's fourteen species on one lamp.\n\nThere's one I've never named, because inspiration hasn't struck yet. Maybe I'll name it after you... on second thought, maybe not.",
  },
  {
    id: 'the_telephone',
    title: 'A Telephone',
    giver: 'hollis',
    desc: 'Hollis at the inn thinks a cafe your size should have a telephone.',
    steps: [
      {
        note: 'Get the cafe up to 40 seats',
        objective: { type: 'seatsEver', count: 40 },
        progress: "Buy enough seats for forty people. You'll need to build new rooms first, then fill them with chairs. Oh, and couches and benches count as three seats each.",
        done: "Oh, I see you have 40 seats now! But can you fill them? See if you can sell 1000 coins' worth of food in a day.",
      },
      {
        note: 'Take 1000 in a single day',
        objective: { type: 'gross', amount: 1000 },
        progress: "Sell a thousand coins' worth of food and drinks in one day.",
        done: "You sold over 1000 in one day! I'd better go find that old phone. Come back later, and I'll give it to you.",
      },
      {
        note: 'See Hollis at the Sleeping Hare',
        objective: { type: 'talk', to: 'hollis' },
        progress: "Come see me anytime. I'm behind the counter, as usual.",
      },
    ],
    reward: {
      money: 0,
      items: [['f_telephone', 1]],
      rep: 0.1,
      friendship: ['hollis'],
    },
    offer: "I've been watching your cafe, and you're really in business now!\n\nHave you thought about doing deliveries? You'd need a telephone for that.\n\nTell you what: if you can get your cafe up to 40 seats, I'll give you the old phone that's sitting in my basement.",
    complete: "*Hollis blows the dust off an old bakelite telephone and sets it on the bar*\n\nHere you go. You can place it like any other furniture. I'd put it near the counter, so you can run and answer it when it rings. It'll ring a few times a day, and always when you're busiest, of course.\n\nTake the order, and deliver it before they get tired of waiting. You'll get paid for the food, plus a nice delivery fee depending on how far you had to walk. If you forget what they ordered or where to go, just check your map.\n\nNow go on. I'm proud of you!",
  },
  {
    id: 'the_usual',
    title: 'The Usual',
    giver: 'fennel',
    desc: "Fennel wants his usual. You don't stock his usual, and he's in no hurry about it.",
    steps: [
      {
        note: 'Buy dandelion cordial at Root & Remedy in Oakhollow',
        objective: { type: 'stock', any: ['dandelion'], count: 2 },
        progress: "Buy two dandelion cordials at Root & Remedy in Oakhollow, so there's one left when I come back.",
        done: 'You got it! You actually did it.\n\nWell, pour me one, then.',
      },
      {
        note: 'Serve Fennel his cordial, next time he is in',
        objective: { type: 'deliver', item: 'dandelion', to: 'fennel', give: false },
        progress: 'Wait for Fennel to come in, then hand him a cordial.',
      },
    ],
    reward: {
      money: 220,
      rep: 0.1,
      items: [['f_painting', 1]],
      friendship: ['fennel'],
    },
    offer: "Good afternoon. I'll have the usual.\n\n...Ah, you don't have the usual. That's all right. Nobody has the usual anymore.\n\nMy usual is dandelion cordial. Root & Remedy in Oakhollow makes it in small batches and barely advertises it. If you stock some, I'll be the most reliable income you've ever had.\n\nNo, I won't go get it myself. I've thought about it, at length.",
    complete: "*Fennel takes one sip and closes his eyes for a little too long*\n\nThat's it. That's exactly it.\n\nWell then, I'll be in at the same time most days. You'll get used to me.\n\nHere, my aunt left me this, and I have nowhere to put it. You have a whole cafe.",
  },
  {
    id: 'the_grey_one',
    title: 'The Gray One',
    giver: 'linnet',
    desc: "Linnet comes in every night hoping to see a cat who doesn't sit with him anymore.",
    night: true,
    steps: [
      {
        note: 'Put a cat bed in the cafe, somewhere he sits',
        objective: { type: 'furniture', place: 'catBed' },
        progress: 'Get a cat bed. The pet shop in Brambleford has them. Put it somewhere near the chairs.',
        done: "A bed, of course! She wanted a bed! My lap just wasn't comfortable enough for her.",
      },
      {
        note: 'Get some cat treats',
        objective: { type: 'item', item: 'treats' },
        progress: "Get some treats from the pet shop too. I'm not above bribery, and neither is she.",
        done: "Good. Now give me the treats. I want her to think they're from me.",
      },
      {
        note: 'Hand the treats to Linnet, after dark',
        objective: { type: 'deliver', item: 'treats', to: 'linnet', give: false },
        progress: "Bring the treats to me instead of giving them to her yourself. That's the whole point.",
      },
    ],
    reward: {
      money: 240,
      rep: 0.08,
      items: [['f_cattower', 1]],
      friendship: ['linnet'],
    },
    offer: "Can I ask you something, as the cat owner?\n\nThe gray cat used to sit with me in the same chair every night, all evening long. She hasn't come near me in six weeks, and I can't stop thinking about it.\n\nI'm not asking you to make her sit with me. You can't make a cat do anything, and even if you could, I wouldn't want that. I just want to know if I did something wrong.",
    complete: "*the gray cat considers the bed, then considers Linnet, and climbs into the bed*\n\n...She's not sitting with me, but she's sitting *near* me.\n\nThat'll do. That'll do just fine. Don't tell anyone I got emotional about this.\n\nHere, take this. She's never used it once.",
  },
  {
    id: 'pun_off',
    title: 'Longest Face Wins',
    giver: 'bruin',
    desc: "Bruin is defending his losing streak at the valley pun contest, and he's run out of material.",
    night: true,
    steps: [
      {
        note: 'Ask Vesper for a pun, up on the downs after dark',
        objective: { type: 'talk', to: 'vesper' },
        progress: "Ask Vesper for a pun. She's up in Hollowdown after dark, somewhere with a view. Ravens are full of puns.",
        done: "You want to know why I sit up here all night?\n\nIt's because the view is *un-perch-edented*.\n\n...For the record, I only said that under duress.",
      },
      {
        note: 'Ask Brine for a pun, night fishing at Saltmere',
        objective: { type: 'talk', to: 'brine' },
        progress: "Ask Brine for a pun. He fishes off the Saltmere shore at night, so ask him while the fish aren't biting.",
        done: "You want a pun from me, at this hour?\n\nFine. What did the tide say to the shore?\n\nNothing. It just *waved*.\n\nNow go away. I've got a line in the water.",
      },
      {
        note: 'Find Nightjar in the dark and ask for a pun',
        objective: { type: 'talk', to: 'nightjar' },
        progress: "Look for Nightjar out in the dark between the towns. They don't stay anywhere for long.",
        done: "*a long churring whirr, and then*\n\nI don't do puns.\n\nI do, however, go wherever it's dark. You could call that a *nocturnal habit*.\n\n*the churring starts up again, sounding a little pleased with itself*",
      },
      {
        note: 'Tell Bruin all three, next time he is in the cafe',
        objective: { type: 'talk', to: 'bruin' },
        progress: "Wait for Bruin to come into your cafe after dark, then tell him all three puns. You won't find him out and about.",
      },
    ],
    reward: { money: 240, rep: 0.08, items: [['cocoa', 3]], friendship: ['bruin'] },
    offer: "You look like someone who can keep a straight face, and I need the opposite of that.\n\nThere's a contest called Longest Face Wins, where the winner is whoever hears the most puns without laughing. I've entered every year and lost every year, and this year I intend to lose *well*.\n\nThe trouble is, I've used up every pun I've got. Go get me three new ones from the folks who are up at this hour. They won't want to give them up, but everybody has one.",
    complete: "*Bruin listens to all three, nodding slowly, like a man being handed tools*\n\nThe raven's pun is cruel, the otter's is wet, and the bird's is barely a pun at all, which makes it the best of the three.\n\nI'm going to lose magnificently. Here, you've earned something warm.",
  },
  {
    id: 'wrong_bird',
    title: 'The Wrong Bird, Repeatedly',
    giver: 'pim',
    desc: 'Pim has spent eleven months trying to find his bird friend Nightjar, and keeps talking to the wrong bird.',
    night: true,
    steps: [
      {
        note: 'Find Nightjar and work out where they go',
        objective: { type: 'talk', to: 'nightjar' },
        progress: 'Go out in the dark between the towns. Nightjar never stays still.',
        done: "*something whooshes close by you, and then it's far away*\n\nYou're looking for me on purpose? That's unusual.\n\nIf you have something for me, I'll be somewhere dark. That's not a riddle.",
      },
      {
        note: 'Buy a little bell at Whisker & Paw in Brambleford',
        objective: { type: 'item', item: 'bell' },
        progress: 'Get a little bell. The pet shop in Brambleford sells them for cats, but a bell is a bell.',
        done: "Good. Now find Nightjar again, but they won't be where they were before.",
      },
      {
        note: 'Give the bell to Nightjar, after dark',
        objective: { type: 'deliver', item: 'bell', to: 'nightjar', give: false },
        progress: "Find Nightjar out in the dark again. They'll be somewhere else this time.",
        done: "*the churring stops*\n\nA bell? Oh, so people will be able to tell it's me. Maybe that kind gentleman I met a while back will be able to find me now.\n\n*there's a pause, and then the sound of a very small bell moving away fast*",
      },
      {
        note: 'Tell Pim it is done',
        objective: { type: 'talk', to: 'pim' },
        progress: 'Go back to Pim in Saltmere, after dark.',
      },
    ],
    reward: { money: 280, rep: 0.1, items: [['f_lamp', 1]], friendship: ['pim'] },
    offer: "Can I be honest with you? I have a problem.\n\nThere's a bird named Nightjar that I met once and want to talk to again, and I've been trying to find them for eleven months. The problem is, my eyesight is very bad, and four different times I've started talking to entirely the wrong bird. One of them was a mailbox.\n\nIn the dark, they all look the same to me. But if Nightjar made a sound, like a bell, I'd know it was them. Would you help me?",
    complete: "*Pim is quiet for a long moment*\n\nI heard it! Out past the hedges, one small bell went by in the wrong direction, really fast.\n\nI didn't manage to say anything, but at least I knew which bird it was, and that's more progress in one evening than I've made in eleven months. Please take this. I have no use for it, and you've been very kind.",
  },
  {
    id: 'mill_watch',
    title: "Nutmeg's Position",
    giver: 'nutmeg',
    desc: 'Nutmeg holds a night position at the old mill, and would rather hold one somewhere warmer.',
    night: true,
    steps: [
      {
        note: 'Ask Grist whether the mill is actually being watched',
        objective: { type: 'talk', to: 'grist' },
        progress: "Ask Grist, during the day, whether he actually hired a night watch for the mill. He's the one who looks after it.",
        done: "A night watch at the mill?\n\nThere's no night watch at the mill, and there never has been. There's nothing in the mill but flour and one very smug little somebody asleep in the hopper.\n\n...Oh. Oh, so that's who that is.",
      },
      {
        note: 'Get a bottle of warm milk to break it to him gently',
        objective: { type: 'item', item: 'milk' },
        progress: "Get some warm milk. Nutmeg's going to want to sit down for this.",
        done: "So you're going to tell him, and have the milk ready when you do. Good thinking.",
      },
      {
        note: 'Take the milk, and the news, to Nutmeg after dark',
        objective: { type: 'deliver', item: 'milk', to: 'nutmeg', give: false },
        progress: "Take the milk to Nutmeg after dark. He's in Thistlewick, or at the mill, or asleep. He's probably asleep.",
      },
    ],
    reward: {
      money: 200,
      rep: 0.06,
      items: [['f_catbed', 1]],
      friendship: ['nutmeg'],
    },
    offer: "I hold a position at the mill. I work nights.\n\nMy position is that I'm at the mill at night, and that's all there is to it. I've held it for two years, and nobody has ever once asked me to do anything, which I took as a compliment.\n\nBut it's awfully cold there. Could you ask Grist whether I'm really needed? Don't lead him on. I want an honest answer, and I want it to be no.",
    complete: "*Nutmeg takes the news with enormous dignity*\n\nTwo years, and nobody ever asked me to do it. I just started, and everyone assumed somebody else had hired me.\n\nIn that case, I resign, effective immediately. I'm taking up a new position at the corner table in your cafe, at night, with warm milk. It's the same duties in a better building.",
  },
  {
    id: 'stone_circle',
    title: 'What The Stones Do',
    giver: 'vesper',
    desc: "Vesper insists the standing stones do something after dark, but won't say what.",
    night: true,
    steps: [
      {
        note: 'Stand in the middle of the standing stones, after dark',
        objective: { type: 'flag', flag: 'stood_in_stones' },
        progress: 'Go to the standing stones up in the hills to the northeast, and stand in the middle of them after dark. Stand right in the middle, not at the edge.',
        done: "They were warm under your hand?! Now go find out how long that's been going on.",
      },
      {
        note: 'Read about the stones at the Reading Room in Brambleford',
        objective: { type: 'flag', flag: 'read_stones' },
        progress: "Read the book about the stones at the Reading Room in Brambleford. Someone bound it by hand, and it's a little damp.",
        done: "Did you see the part about a saucer of milk that came back empty? That's what I wanted you to find.",
      },
      {
        note: 'Get a bottle of milk',
        objective: { type: 'item', item: 'milk' },
        progress: 'Buy milk at the grocer in Brambleford. Any milk will do.',
        done: 'Okay, up you go, then. Leave the milk in the middle of the stones and step back.',
      },
      {
        note: 'Leave the milk at the standing stones, after dark',
        objective: { type: 'flag', flag: 'left_milk' },
        progress: 'Leave the milk in the middle of the stones after dark, then wait a moment.',
      },
    ],
    reward: {
      money: 260,
      rep: 0.08,
      items: [['catnip', 1]],
      flags: ['hint_stones'],
    },
    offer: "You want to know what I do up here all night? I watch the stones.\n\nNo, I'm not telling you why. If I tell you, you'll go up there expecting it, and you'll only see what you expected to see. Go stand in the middle of them after dark, then come back and tell me about it.\n\nAnd bring a saucer of milk. You'll see why.",
    complete: "So now you know.\n\nEveryone who's ever left a saucer of milk there has found it empty, every single time, for as long as anyone's been writing it down.\n\nBut nobody has ever seen what drinks it, and I've been watching for four years.",
  },
  {
    id: 'lit_window',
    title: 'A Lit Window',
    giver: 'tallow',
    desc: 'Tallow thinks the cafe is wasting its evenings.',
    night: true,
    steps: [
      {
        note: 'Put a lamp in the cafe',
        objective: { type: 'furniture', place: 'lampIn' },
        progress: 'Buy a floor lamp at Velvet & Oak in Thistlewick and put it in the cafe.',
        done: 'Good. Now leave the sign on OPEN past sunset, and make sure you actually stay there.',
      },
      {
        note: 'Serve somebody in the cafe after dark',
        objective: { type: 'flag', flag: 'served_after_dark' },
        progress: 'Keep the sign on OPEN past sunset and stand behind the counter yourself. Somebody will come.',
      },
    ],
    reward: { money: 220, rep: 0.12, friendship: ['tallow'] },
    offer: "Your place is dark at night, and that's a waste of a good building.\n\nA lit window after sunset is the most inviting thing there is. People walk toward it without even deciding to.\n\nPut a lamp in that cafe of yours, then stay open past sunset and see who shows up.",
    complete: "I walked by last night, and there it was: a warm square of light with cats in it.\n\nI stood there like an idiot for a full minute.\n\nThat's what this business is all about.",
  },
  {
    id: 'music_night',
    title: 'Somewhere to Play',
    giver: 'lark',
    desc: 'Lark would love a piano to play in a warm room.',
    objective: { type: 'furniture', place: 'piano' },
    progress: 'Get a piano into the cafe. The flea market in Thistlewick gets one in every now and then.',
    reward: { money: 260, rep: 0.12, friendship: ['lark'] },
    offer: "I sing for anyone who'll listen, which out here is mostly sheep.\n\nIf you put a piano in that cafe of yours, I'll come play every evening for free. Check the flea market, because they get one in every now and then.",
    complete: "You *got* one!\n\nOkay, I'll be here every evening from now on. Your regulars are about to fall in love with this place.",
  },
  {
    id: 'cat_toys',
    title: 'Cat Enrichment',
    giver: 'marigold',
    desc: "Marigold is worried the cats in your cafe won't be happy until they have toys to play with.",
    objective: { type: 'stock', any: ['toy_yarn'], count: 1 },
    progress: '',
    reward: {
      money: 0,
      rep: 1,
      friendship: ['marigold'],
      journal: 'Your cats have been more playful, and purring more, since you gave them toys. The customers noticed too.',
    },
    offer: "Buy your cats some toys! They'll be happier, and your customers will enjoy them more.",
    complete: "If you give your cats safety, food, care, and things to do, they'll repay you and your customers with kindness.\n\nYour cats are already happier.",
  },
];
