// The quests, as plain data.
//
// Written by the editor in tools/editor. Everything in here is data: no
// functions, no imports, nothing that cannot survive a round trip through
// JSON. Hand edits are welcome and will be kept, but the formatting and any
// comments outside this header are replaced the next time the editor saves.
// A prose note about a particular entry belongs in its own `note` field,
// which is data and does survive.

export const QUESTS = [
  {
    id: 'first_beans',
    title: 'Something To Sell',
    giver: 'pip',
    desc: 'Pip suggested stocking coffee and something sweet before opening properly.',
    objective: { type: 'stock', any: ['house_coffee', 'black_tea'], count: 6 },
    progress: 'Stock six portions of coffee or tea. Buy them from the grocer in Brambleford.',
    reward: { money: 60, items: [['cookie', 4]] },
    offer: "You've opened a cafe with nothing to sell in it. Bold.\n\nGet six portions of coffee or tea and I'll throw in some cookies for nothing.",
    complete: "There we are. Now you're a business.\n\nTake these cookies. Don't tell anyone I'm soft.",
  },
  {
    id: 'honey_run',
    title: 'A Jar of Sunlight',
    giver: 'dough',
    desc: "Dough wants a jar of Clover's honey from Oakhollow to work into a scone recipe.",
    objective: { type: 'item', item: 'honey', count: 1 },
    progress: 'Buy a jar of honey from the beekeeper in Oakhollow. Follow the road east and then north, and look for the very large tree.',
    reward: { money: 140, flags: ['recipe_honey'], items: [['honey_scone', 3]] },
    offer: "Clover keeps bees out at Oakhollow, east through the woods.\n\nBring me a jar and I'll make honey scones. People will flock to your cafe for it.",
    complete: "That's the stuff. Here are the honey scones.",
  },
  {
    id: 'lost_bell',
    title: 'The Lost Bell',
    giver: 'marigold',
    desc: 'A little bell with a name scratched inside was found on the road. Marigold thinks it belongs to somebody in Saltmere.',
    objective: { type: 'deliver', item: 'lost_bell', to: 'shrimp' },
    progress: 'Take the bell to Shrimp in Saltmere, on the coast to the south-west. He is the otter by the water.',
    reward: { money: 180, friendship: ['shrimp'], items: [['bell', 1]] },
    offer: "Somebody handed this in. There's a name scratched inside — can't read it, but it's a Saltmere sort of name.\n\nTake it down to the coast and ask around?",
    complete: 'Thank you for bringing it back. Really.',
  },
  {
    id: 'flower_delivery',
    title: 'Flowers for Somebody',
    giver: 'nettle',
    desc: 'Nettle picked wildflowers for someone in Hollowdown but is too shy to deliver them.',
    objective: { type: 'deliver', item: 'wildflowers', to: 'chalk' },
    progress: 'Take the flowers to Chalk in Hollowdown, up on the chalk hills to the north.',
    reward: {
      money: 90,
      friendship: ['chalk', 'nettle'],
      flags: ['hint_taxi'],
      journal: 'The taxi birds will fly you anywhere you have already been. There is a perch in every town, and they work seven in the morning to seven at night.',
    },
    offer: "So..... this is um, embarrassing. I picked these for someone up in Hollowdown and um... now I can't possibly hand them over myself.\n\nWould you? They're for Chalk. The cute squirrel. You'll know them.",
    complete: "Oh. Oh! From Nettle? Well. Well well well.\n\nHere's a tip: did you know the birds run a taxi service? There's a perch in every town.",
  },
  {
    id: 'sea_shell',
    title: 'Something for the Window',
    giver: 'juniper',
    note: 'Asking around IS the job until somebody answers. Once Shrimp has said where the shell went the note has to say so: it is a whole errand away by then, and nobody remembers a line of dialogue from two towns ago.',
    desc: 'Juniper thinks your cafe needs a spiral shell on the windowsill.',
    objective: { type: 'item', item: 'seashell', count: 1 },
    progress: 'Ask around Saltmere about a big spiral shell. Somebody down there had one.',
    progressWhen: [
      {
        flag: 'heard_hint_shrimp',
        text: 'Shrimp says Moth has the shell. Moth is a small grey mouse in Brambleford, out after dark counting moths on the lamps. Go and see what he wants for it.',
      },
    ],
    reward: { money: 110, items: [['f_plant', 1]], rep: 0.04 },
    offer: "Your place needs a *thing*. An pretty object. Something with a story.\n\nA big spiral shell, that's what. There was one down at Saltmere — I'd ask about rather than go looking, mind. That beach has been picked over since before I was born.",
    complete: 'Perfect. Absolutely perfect.\n\nHere, have this fern too. Trust me on the fern.',
  },
  {
    id: 'clear_the_path',
    title: 'The Fallen Chalk',
    giver: 'brook',
    desc: 'A slab of chalk is blocking the river bridge on the road east. Brook says the right tool would move it.',
    objective: { type: 'flag', flag: 'barrier_eastpass' },
    progress: 'Buy a chalk pick at the Chalk Pit Store in Hollowdown, then follow the road due east out of town to the river. You cannot miss the bridge, or the chalk sitting on it.',
    reward: { money: 260, rep: 0.05 },
    offer: "Water's high after the rain, and it took the bank out from under a chalk face east of here. Great lump of it came down right across the middle of the bridge, and it is deep water either side.\n\nThat was the road to Thistlewick, that was. You can still get there the long way round, by Hollowdown and Oakhollow, but it is the best part of an hour nobody should have to walk twice.\n\nGet a pick — the Chalk Pit Store up in Hollowdown has them — and move it. Everyone in this town will be quietly grateful and not one of them will say so.",
    complete: "You moved it? On your own?\n\nGreat! The bridge is open again, no more trailing all the way round by Hollowdown to get to Thistlewick.\n\nTake this, and don't argue.",
  },
  {
    id: 'bramble_path',
    title: 'The Way to the Mill',
    giver: 'grist',
    desc: 'Brambles have swallowed the path to the old mill. Grist would like it opened.',
    objective: { type: 'flag', flag: 'barrier_millpath' },
    progress: 'Buy hedge shears at the Chalk Pit Store in Hollowdown, then go to the little bridge on the mill track, north-east of here.',
    reward: { money: 220, items: [['valley_map', 1]] },
    offer: "The old mill's my family's, technically. Can't reach it — the brambles have taken the whole bridge across to it. Grown right over the deck, thick as rope.\n\nShears would do it. The hardware place up in Hollowdown sells them.",
    complete: "You got through! And you didn't fall through the floor. Both good.\n\nHere's a map of the valley. It's wrong about the north but it's better than nothing.",
  },
  {
    id: 'four_cats',
    title: 'A Proper Cattery',
    giver: 'thimble',
    desc: 'Thimble counts your cats every time they walk past and would like there to be more of them.',
    objective: { type: 'cats', count: 4 },
    progress: 'Adopt four cats. Whisker & Paw down the lane sells them.',
    reward: { money: 200, rep: 0.06 },
    offer: "I count your cats when I walk past. There are not enough of them.\n\nGet to four and I'll... I'll be pleased. And I'll give you something for the trouble.",
    complete: 'Four! I counted twice.\n\nHere. Spend it on something for them, not for you.',
  },
  {
    id: 'good_coat',
    title: 'Show Me a Silky Coat',
    giver: 'suds',
    desc: 'Suds wants to see what proper food does to a cat, not just grooming.',
    objective: { type: 'coat', quality: 1.12 },
    progress: 'Feed a cat fresh fish or gourmet tins for a few days running. Kibble and good food will not do it.',
    reward: {
      money: 240,
      items: [['brush', 1]],
      flags: ['hint_fish'],
      journal: 'Kelp lands fresh fish in Saltmere every morning, and is sold out by noon. A cat fed on it comes up glossy in under a week.',
    },
    offer: "Everyone thinks grooming is the whole story. It isn't. Food's half of it.\n\nFeed your cats fish or the gourmet tins for a few days — the cheap stuff will not show — and bring one back to me.",
    complete: "*Now* look at that. That's what I'm talking about.\n\nRemember to brush them between visits. And go and see Kelp in Saltmere about fish. Before noon, mind.",
  },
  {
    id: 'first_extension',
    title: 'Room to Breathe',
    giver: 'trowel',
    desc: "Trowel will believe you're serious once you've actually built something.",
    objective: { type: 'rooms', count: 2 },
    progress: 'Hire workers from me, then build one more room onto the cafe.',
    reward: { money: 300, rep: 0.08 },
    offer: "Everyone talks about renovating. Almost nobody does it.\n\nHire a crew, buy the materials, add a room to your place. Then come back and we'll talk about doing it properly.",
    complete: "You did it. And it's not bad.\n\nNow you're a customer. Next time we'll do something ambitious.",
  },
  {
    id: 'busy_day',
    title: 'A Day Worth Having',
    giver: 'ledger',
    desc: 'Ledger would like to see you turn a genuinely good profit in a single day.',
    objective: { type: 'profit', amount: 400 },
    progress: 'Clear four hundred in profit in a single day, after all your costs.',
    reward: { money: 350, rep: 0.1 },
    offer: "Advice is cheap. Results aren't.\n\nClear four hundred profit in one day — after wages, after cat food, after everything. Then I'll take you seriously.",
    complete: "Four hundred clear. On a Tuesday, no less.\n\nYou've got a business. Congratulations. Now don't get comfortable.",
  },
  {
    id: 'rare_cat',
    title: 'A Cat of Distinction',
    giver: 'sable',
    desc: 'Sable will only take you seriously once you own a rare breed.',
    objective: { type: 'rarecat' },
    progress: 'Adopt a rare breed. I sell them here, on the days I open.',
    reward: { money: 400, items: [['ribbon', 2]], rep: 0.08 },
    offer: 'Common cats are lovely and I mean nothing against them.\n\nBut bring a rare coat into that room and watch what happens to your profit. Come back when you have one of mine.',
    complete: 'There. Now your cafe has a *centrepiece*.\n\nTake these ribbons. Presentation is most of it.',
  },
  {
    id: 'lighthouse_log',
    title: 'The Keeper Who Left',
    giver: 'slate',
    desc: "Slate wants to know what's in the lighthouse logbook.",
    objective: { type: 'item', item: 'logbook', count: 1 },
    progress: "Search the keeper's table in the lighthouse, west along the coast past Saltmere.",
    reward: { money: 300, items: [['lantern', 1]], rep: 0.05 },
    offer: "Gullrock Light. Still burning, no keeper. Nobody will go and look.\n\nThere's a logbook in there. Bring it to me and I'll make it worth the walk.",
    complete: "Eleven years of tides and weather... and one line, near the end.\n\n'The cat has stopped coming. I shall wait a while longer.'\n\nHm. Take this lantern. Somebody should keep something burning.",
  },
  {
    id: 'lane_end_hedge',
    title: 'The Hedge at Lane End',
    giver: 'button',
    desc: "Button's hedge moves at night. Button would like it to stop.",
    steps: [
      {
        note: 'Look at the hedge at the end of the lane, after dark',
        objective: { type: 'flag', flag: 'saw_the_hedge' },
        evidence: 'saw_the_hedge',
        progress: 'Go and look at the hedge after dark. It does nothing in daylight — I have stood there checking, repeatedly.',
        done: 'You SAW it? Ha! HA! I am not daft, then. Right. What do we do about it?',
      },
      {
        note: 'Speak to whatever is in the hedge',
        objective: { type: 'talk', to: 'woofers' },
        progress: 'Go back to the hedge after dark and talk to whatever is in it. It will not be me who does it.',
        done: "*the shape in the hedge lifts its head*\n\nYou can see me? Nobody has been able to see me in a very long while.\n\nI lost my collar. It was gold, and it had my name upon it, and I've been looking in this hedge for — some time. I no longer recall where I had it last.\n\nI do not recall a great deal. I am fairly sure I was IMPORTANT ENOUGH TO APPEAR IN A HISTORY BOOK.",
      },
      {
        note: 'Read about Sir Woofers at the Reading Room in Brambleford',
        objective: { type: 'flag', flag: 'read_town_history' },
        evidence: 'read_town_history',
        progress: 'Read the town history at the Reading Room in Brambleford. Somebody will have written about famous dog dying — somebody writes everything down.',
        done: 'Saltsouth Pier. 1800. He wore it to the opening and never came home with it.\n\nAnd Saltsouth, according to the margin, is Saltmere.',
      },
      {
        note: 'Search the mud at the end of Saltmere Pier',
        objective: { type: 'item', item: 'golden_collar', count: 1 },
        evidence: 'got_collar',
        progress: 'Go to the end of the pier at Saltmere and search the mud under it, not on it.',
        done: 'Two hundred years in the mud, and still bright.',
      },
      {
        note: 'Take the collar back to Sir Woofers, after dark',
        objective: {
          type: 'deliver',
          item: 'golden_collar',
          to: 'woofers',
          give: false,
        },
        progress: 'Take the collar back to the hedge after dark. He is always at the hedge.',
        done: "My soul can rest now that I've been reunited with my prized golden collar.\n\nThis collar brings back cherished memories, I thank you.",
      },
    ],
    reward: {
      money: 400,
      rep: 1,
      friendship: ['button'],
      items: [['catnip', 5]],
      journal: "Sir Woofer's soul can rest now that he's been reunited with his golden collar.",
    },
    offer: 'Right. Short legs, long opinions, and here is one of them.\n\nThe hedge at the end of my lane MOVES. At night. Not the wind — one bit of it, going up and down like something is working along the bottom of it looking for a sock.\n\nI have barked at it. I have barked at it a great deal. It does not care, which is frankly insulting. You have cats. You are used to nonsense. Would you go and look?',
    complete: 'Oh. Oh, that IS mine. That is my collar.\n\n*the very old dog stands still for the first time in two hundred years*\n\nThey put my name on it, you know. At the opening. There was a ribbon and everything.\n\nThank you. Thank you. I shall stop bothering the hedge.',
  },
  {
    id: 'moth_count',
    title: 'Fourteen Species',
    giver: 'moth',
    desc: 'Moth counts moths, and has run out of light to count them by.',
    night: true,
    requires: 'heard_hint_shrimp',
    steps: [
      {
        note: 'Buy a storm lantern at the Chalk Pit Store in Hollowdown',
        objective: { type: 'item', item: 'lantern', count: 1 },
        progress: 'Buy a storm lantern at the Chalk Pit Store in Hollowdown. Ask for a storm lantern, not a nice one.',
        done: "That's the one. Now — where's dark and still and has a lamp?",
      },
      {
        note: 'Take the lantern to Moth, after dark',
        objective: { type: 'deliver', item: 'lantern', to: 'moth', give: false },
      },
    ],
    reward: {
      money: 150,
      items: [['seashell', 1]],
      friendship: ['moth'],
      rep: 0.1,
      journal: 'Moth counts moths at night. So when does he sleep? In any case, after helping him out with improved lighting for his night time pass time, he kindly rewarded me with a spiral seashell.',
    },
    offer: "You're up late. Good. Nobody's ever awake this late.\n\nI count moths, you see. On the lamps. But the lamps in this town are dreadful and half of them are out.\n\nI'm fairly sure I've been counting the same moth eleven times on account of poor lighting.\n\nThere's a proper storm lantern to be had at the hardware place up in Hollowdown. Bring me one and I'll show you something.",
    complete: "*Moth holds the lantern up and the air fills — properly fills — with fluttering wings as moths draw close round the upheld lantern*\n\nFourteen. Fourteen species on one lamp. \n\nThere's one I've never named, the inspiration hasn't hit me yet. Maybe I'll name it after you... on second thought, maybe not.",
  },
  {
    id: 'the_telephone',
    title: 'A Line Out',
    giver: 'hollis',
    desc: 'Hollis at the inn thinks a cafe your size ought to have a telephone.',
    steps: [
      {
        note: 'Get the cafe up to 40 seats',
        objective: { type: 'seatsEver', count: 40 },
        progress: 'Get the cafe up to forty seats. Build the rooms first, then fill them — sofas and benches count for three each.',
        done: 'Show me a day that fills forty seats at your cafe.',
      },
      {
        note: 'Take 1000 in a single day',
        objective: { type: 'gross', amount: 1000 },
        progress: 'Take a thousand in one day, before costs. The morning card keeps the record.',
        done: "That'll do. Now go and pay the phone company in Hollowdown, ask for a new line.",
      },
      {
        note: 'Save up 600 to pay the phone company',
        objective: { type: 'money', amount: 600 },
        progress: 'Save up six hundred for the phone company. They do not do favours and neither do I.',
        done: 'Good. Come and see me and we will get you connected.',
      },
      {
        note: 'See Hollis at the Sleeping Hare',
        objective: { type: 'talk', to: 'hollis' },
        progress: 'Come and see me at the Sleeping Hare in Brambleford. I am behind the bar, as ever.',
      },
    ],
    reward: {
      money: -600,
      items: [['f_telephone', 1]],
      rep: 0.1,
      friendship: ['hollis'],
    },
    offer: "I have been watching your place fill up! You are past being a nice little spot, you are a business.\n\nHave you thought about doing deliveries? You'll need a telephone.\n\nThe phone company is in Hollowdown and they'll need to be paid to set up an account. If you do that, I'll give you my old phone I've got sitting in the cellar.",
    complete: '*Hollis blows the dust off a bakelite telephone and sets it on the bar*\n\nPut it where you can hear it from the pantry. It will ring a few times a day and it will only ring when you are busy — that is the nature of the thing.\n\nTake the order, deliver it before too long, and get paid for the walk as well as the food.',
  },
  {
    id: 'the_usual',
    title: 'The Usual',
    giver: 'fennel',
    desc: "Fennel would like his usual. You don't stock his usual and he's in no hurry about it.",
    steps: [
      {
        note: 'Buy dandelion cordial at Root & Remedy in Oakhollow',
        objective: { type: 'stock', any: ['dandelion'], count: 2 },
        progress: 'Buy two dandelion cordials at Root & Remedy in Oakhollow, so there is one left when I come back.',
        done: 'You got it. You actually did it.\n\nPour me one, then.',
      },
      {
        note: 'Serve Fennel his cordial, next time he is in',
        objective: { type: 'deliver', item: 'dandelion', to: 'fennel', give: false },
        progress: 'Wait for Fennel to come in, then hand him a cordial.',
      },
    ],
    reward: {
      money: 220,
      rep: 0.1,
      items: [['f_painting', 1]],
      friendship: ['fennel'],
    },
    offer: "Afternoon. I'll have the usual.\n\n...Ah. You don't do the usual. That's all right. Nobody does the usual any more.\n\nDandelion cordial. Root & Remedy in Oakhollow make it, in small batches, badly advertised. Get some in and I shall become the most reliable income you have ever had.\n\nNo, I won't fetch it myself. I have thought about it. At length.",
    complete: "*Fennel takes one sip and closes his eyes for slightly too long*\n\nThat's it. That is precisely it.\n\nRight. Same time most days, then. You'll get used to me.\n\nHere — my aunt left me this and I have nowhere to put it. You have a whole cafe.",
  },
  {
    id: 'the_grey_one',
    title: 'The Grey One',
    giver: 'linnet',
    desc: 'Linnet comes in every night for a cat who has stopped sitting with him.',
    night: true,
    steps: [
      {
        note: 'Put a cat bed in the cafe, somewhere he sits',
        objective: { type: 'furniture', place: 'catBed' },
        progress: 'Get a cat bed. The pet shop in Brambleford has them. Put it somewhere near the chairs.',
        done: 'A bed, of course, she wanted a bed! My lap was not comfortable for her.',
      },
      {
        note: 'Get some cat treats',
        objective: { type: 'item', item: 'treats' },
        progress: 'Get treats from the pet shop again. I am not above bribery and neither is she.',
        done: 'Good. Now give me the treats. I would like her to think it was me who brought them.',
      },
      {
        note: 'Hand the treats to Linnet, after dark',
        objective: { type: 'deliver', item: 'treats', to: 'linnet', give: false },
        progress: 'Give them to him rather than doing it yourself. That is the whole point.',
      },
    ],
    reward: {
      money: 240,
      rep: 0.08,
      items: [['f_cattower', 1]],
      friendship: ['linnet'],
    },
    offer: 'May I ask you something, as the one who owns the cats?\n\nThe grey cat used to sit with me. Every night, same chair, the whole evening. Six weeks now she has not come near me and I have been thinking it over and over.\n\nI am not asking you to make her. You cannot make a cat do anything, and I would not want her if you could. I am asking whether there is something I did wrong.',
    complete: '*the grey cat considers the bed, considers Linnet, and gets into the bed*\n\n...She is not sitting with me. She is sitting *near* me.\n\nThat will do. That will do very nicely. Do not tell anyone I got emotional about this.\n\nTake this. She has never once used it.',
  },
  {
    id: 'pun_off',
    title: 'Longest Face Wins',
    giver: 'bruin',
    desc: 'Bruin defends his losing streak at the valley pun contest and has run out of material.',
    night: true,
    steps: [
      {
        note: 'Ask Vesper for a pun, up on the downs after dark',
        objective: { type: 'talk', to: 'vesper' },
        progress: 'Ask Vesper for a pun. She is up in Hollowdown after dark, somewhere with a view. Ravens are full of them.',
        done: 'Why do I sit up here all night?\n\nBecause the view is *un-perch-edented*.\n\n...I want it on the record that I said that under duress.',
      },
      {
        note: 'Ask Brine for a pun, night fishing at Saltmere',
        objective: { type: 'talk', to: 'brine' },
        progress: 'Ask Brine for a pun. He fishes off the Saltmere shore at night — ask while the fish are not biting.',
        done: "You want a pun. From me. At this hour.\n\nFine. What did the tide say to the shore?\n\nNothing. It just *waved*.\n\nNow go away, I've a line out.",
      },
      {
        note: 'Find Nightjar in the dark and ask for a pun',
        objective: { type: 'talk', to: 'nightjar' },
        progress: 'Look for Nightjar out in the dark between the towns. They do not stay anywhere for long.',
        done: '*a long churring whirr, then*\n\nI do not do puns.\n\nI do, however, go where it is dark. You could call that a *nocturnal habit*.\n\n*the churring resumes, sounding very slightly pleased with itself*',
      },
      {
        note: 'Tell Bruin all three, next time he is in the cafe',
        objective: { type: 'talk', to: 'bruin' },
        progress: 'Wait for Bruin to let himself into your cafe after dark, then tell him all three. He does not go out to be found.',
      },
    ],
    reward: { money: 240, rep: 0.08, items: [['cocoa', 3]], friendship: ['bruin'] },
    offer: "Right. You look like someone who can keep a straight face. I need the opposite of that.\n\nThere's a contest. Longest Face Wins — whoever hears the most puns without laughing. I have entered every year and lost every year, and I intend to lose *well*.\n\nOnly I have used everything I have. Go and get me three from the folk who are up at this hour. They will not want to give them to you. Everybody has one.",
    complete: "*Bruin listens to all three, nodding slowly, like a man being handed tools*\n\nThe raven's is cruel, the otter's is wet, and the one from the bird is barely a pun at all — which makes it the best of the three.\n\nI shall lose magnificently. Here. You have earned something warm.",
  },
  {
    id: 'wrong_bird',
    title: 'The Wrong Bird, Repeatedly',
    giver: 'pim',
    desc: 'Pim has been trying to find his bird friend Nightjar for eleven months and keeps talking to the wrong bird.',
    night: true,
    steps: [
      {
        note: 'Find Nightjar and work out where they go',
        objective: { type: 'talk', to: 'nightjar' },
        progress: 'Go out in the dark between the towns. Nightjar does not keep still.',
        done: "*a whoosh close by you and then far away*\n\nYou are looking for me on purpose. That's unusual.\n\nIf you have something for me, I will be somewhere dark. That is not a riddle.",
      },
      {
        note: 'Buy a little bell at Whisker & Paw in Brambleford',
        objective: { type: 'item', item: 'bell' },
        progress: 'Get a little bell. The pet shop in Brambleford sells them for cats, but a bell is a bell.',
        done: 'Good. Now find them again — and they will not be where they were.',
      },
      {
        note: 'Give the bell to Nightjar, after dark',
        objective: { type: 'deliver', item: 'bell', to: 'nightjar', give: false },
        progress: 'Find Nightjar out in the dark again. They will be somewhere else this time.',
        done: '*the churring stops*\n\nA bell? Oh, so someone can tell it is me. Maybe that kind gentleman I met some time ago will find me\n\n*a pause, and then the sound of a very small bell moving away at speed*',
      },
      {
        note: 'Tell Pim it is done',
        objective: { type: 'talk', to: 'pim' },
        progress: 'Go back to Pim down at Saltmere, after dark.',
      },
    ],
    reward: { money: 280, rep: 0.1, items: [['f_lamp', 1]], friendship: ['pim'] },
    offer: 'May I be honest with you? I have a difficulty.\n\nThere is a bird friend I met once and want to talk to again. Their name is Nightjar. I have been trying to find them for eleven months. The difficulty is that I have very bad eyesight, and on four separate occasions I started talking to entirely the wrong bird. One of them was a post box.\n\nThey all look the same in the dark to my eyes, you see. If the bird I want to talk to were to make a sound — a bell, say — I would know. Would you help?',
    complete: '*Pim is quiet for a long moment*\n\nI heard it. Out past the hedges. One small bell, going the wrong way really fast.\n\nI did not manage to say anything. But I knew which one it was, and that is eleven months of progress in an evening. Take this. I have no use for it and you have been very kind.',
  },
  {
    id: 'mill_watch',
    title: "Nutmeg's Position",
    giver: 'nutmeg',
    desc: 'Nutmeg holds a night position at the old mill, and would like to hold it somewhere warmer.',
    night: true,
    steps: [
      {
        note: 'Ask Grist whether the mill is actually being watched',
        objective: { type: 'talk', to: 'grist' },
        progress: 'Ask Grist, in daylight, whether he employs a night watch at the mill. He is the one who keeps it.',
        done: "A night watch? At the mill?\n\nThere is no night watch at the mill. There has never been a night watch at the mill. There is nothing in the mill but flour and one very smug something asleep in the hopper.\n\n...Oh. Oh, that's who that is.",
      },
      {
        note: 'Get a bottle of warm milk to break it to him gently',
        objective: { type: 'item', item: 'milk' },
        progress: 'Get warm milk. Nutmeg is not going to take this standing up.',
        done: 'You are going to tell him, and you are going to have the milk ready. Good instinct.',
      },
      {
        note: 'Take the milk, and the news, to Nutmeg after dark',
        objective: { type: 'deliver', item: 'milk', to: 'nutmeg', give: false },
        progress: 'Take the milk to Nutmeg after dark. He is in Thistlewick, or at the mill, or asleep. Probably asleep.',
      },
    ],
    reward: {
      money: 200,
      rep: 0.06,
      items: [['f_catbed', 1]],
      friendship: ['nutmeg'],
    },
    offer: "I hold a position. At the mill. Nights.\n\nThe position is that I am at the mill, at night. That's all. Nothing more. I have held it for two years and I have never once been asked to do anything, which I had taken as a compliment.\n\nIt is, however, extremely cold. Would you find out from Grist whether I am, strictly speaking, required? Do not lead him on. I want an honest answer and I want it to be no.",
    complete: '*Nutmeg receives this news with enormous dignity*\n\nTwo years. Nobody asked me. I simply started, and everyone assumed somebody else had hired me.\n\nThen I shall resign, effective immediately, and I shall take up a new position: the corner table in your cafe, nights, warm milk. Same duties. Better building.',
  },
  {
    id: 'stone_circle',
    title: 'What The Stones Do',
    giver: 'vesper',
    desc: 'Vesper insists the standing stones do something after dark, and will not say what.',
    night: true,
    steps: [
      {
        note: 'Stand in the middle of the standing stones, after dark',
        objective: { type: 'flag', flag: 'stood_in_stones' },
        progress: 'Go to the standing stones on the high downs to the north-east and stand in the middle of them after dark. Not from the edge.',
        done: 'Warm, were they? Under your hand? Good. Now go and find out how long that has been going on.',
      },
      {
        note: 'Read about the stones at the Reading Room in Brambleford',
        objective: { type: 'flag', flag: 'read_stones' },
        progress: 'Read the book on the stones at the Reading Room in Brambleford. Somebody bound it by hand and it is slightly damp.',
        done: 'A saucer of milk. Returned empty. That is the entry I wanted you to find.',
      },
      {
        note: 'Get a bottle of milk',
        objective: { type: 'item', item: 'milk' },
        progress: 'Buy milk at the grocer in Brambleford. Any milk will do.',
        done: 'Right. Up you go, then. Leave it in the middle and step back.',
      },
      {
        note: 'Leave the milk at the standing stones, after dark',
        objective: { type: 'flag', flag: 'left_milk' },
        progress: 'Leave the milk in the middle of the stones after dark, then wait a moment.',
      },
    ],
    reward: {
      money: 260,
      rep: 0.08,
      items: [['catnip', 1]],
      flags: ['hint_stones'],
    },
    offer: "You want to know what I do up here all night? I watch the stones.\n\nNo, I'm not telling you. If I tell you, you'll go up expecting it, and you'll see what you expected. Go and stand in the middle of them after dark and come back to me.\n\nBring a saucer of milk. You'll see why.",
    complete: 'So now you know.\n\nEveryone who has ever left a saucer there has found it empty. Every single one. For as long as anyone has been writing it down.\n\nNobody has ever seen what drinks it. I have watched for four years.',
  },
  {
    id: 'lit_window',
    title: 'A Lit Window',
    giver: 'tallow',
    desc: 'Tallow thinks the cafe is wasting its evenings.',
    night: true,
    steps: [
      {
        note: 'Put a lamp in the cafe',
        objective: { type: 'furniture', place: 'lampIn' },
        progress: 'Buy a floor lamp at Velvet & Oak in Thistlewick and put it in the cafe.',
        done: 'Good. Now leave the sign on OPEN past sunset and actually be in there.',
      },
      {
        note: 'Serve somebody in the cafe after dark',
        objective: { type: 'flag', flag: 'served_after_dark' },
        progress: 'Keep the sign on OPEN past sunset and stand behind the counter yourself. Somebody will come.',
      },
    ],
    reward: { money: 220, rep: 0.12, friendship: ['tallow'] },
    offer: "Your place is dark at night. That's a waste of a building.\n\nA lit window after sunset is the most inviting thing there is. People walk towards it without deciding to.\n\nPut a lamp in that cafe of yours, then keep the door open past sunset and see who comes.",
    complete: "I walked past last night and there it was. Warm square of light with cats in it.\n\nI stood there like an idiot for a full minute.\n\nThat's the trade. That's all of it.",
  },
  {
    id: 'music_night',
    title: 'Somewhere to Play',
    giver: 'lark',
    desc: 'Lark would love a piano to play in a warm room.',
    objective: { type: 'furniture', place: 'piano' },
    progress: 'Get a piano into the cafe. The flea market in Thistlewick turns one up now and then.',
    reward: { money: 260, rep: 0.12, friendship: ['lark'] },
    offer: "I sing for anyone who'll listen, which out here is mostly sheep.\n\nPut a piano in that cafe of yours and I'll come every evening. Free. Ask the flea market, they get one now and then.",
    complete: "You *got* one.\n\nRight. I'm here every evening from now on. Your regulars are about to get very fond of this place.",
  },
  {
    id: 'cat_toys',
    title: 'Cat enrichment',
    giver: 'marigold',
    desc: 'Marigold is concerned that the cats in the cafe will not be content until they have toys t play with.',
    objective: { type: 'stock', any: ['toy_yarn'], count: 1 },
    progress: '',
    reward: { money: 0, rep: 1, friendship: ['marigold'] },
    offer: "Cats who live boring lives will never be content. \n\nA good pet owner provides some excitement and stimulate the minds of their animal companions.\n\nBuy your cats some toys! The cats will be happier, and your customers will enjoy the improvement. It's a win win deal.",
    complete: "Now you're a proper cat caretaker.\n\nYour cats are happier and more satisfied with life already.",
  },
];
