// Static description of the valley: five settlements, the shops in them, the
// villagers who live there, and what everyone has to say.

export const TOWNS = [
  {
    id: 'brambleford',
    name: 'Brambleford',
    blurb: 'A muddle of thatch and crooked lanes around a duck-pond.',
    x: 96, y: 168, w: 44, h: 34,
    style: { wall: '#efe2c8', roofs: ['#c86a4a', '#d0a659', '#5a6472'], timbered: true },
    music: 'town',
  },
  {
    id: 'hollowdown',
    name: 'Hollowdown',
    blurb: 'Terraced into the chalk hills; everything is up or down some steps.',
    x: 208, y: 68, w: 40, h: 32,
    style: { wall: '#e6dcc2', roofs: ['#5a6472', '#7d8794', '#c86a4a'], timbered: false },
    music: 'town',
  },
  {
    id: 'saltmere',
    name: 'Saltmere',
    blurb: 'Fishing cottages, tarred boats, and gulls with opinions.',
    x: 62, y: 234, w: 38, h: 26,
    style: { wall: '#dfe6e8', roofs: ['#4f6a72', '#7d8794', '#b2624b'], timbered: false },
    music: 'town',
  },
  {
    id: 'thistlewick',
    name: 'Thistlewick',
    blurb: 'Market town. If it exists, somebody here is selling it at a markup.',
    x: 266, y: 196, w: 46, h: 34,
    style: { wall: '#f0e4cc', roofs: ['#b2624b', '#c86a4a', '#d0a659'], timbered: true },
    music: 'town',
  },
  {
    id: 'oakhollow',
    name: 'Oakhollow',
    blurb: 'Six houses and a very large tree, deep in the woods.',
    x: 292, y: 84, w: 26, h: 22,
    style: { wall: '#e8dcc2', roofs: ['#7d8794', '#d0a659', '#6b7d54'], timbered: true },
    music: 'field',
  },
];

/**
 * Shops. `sign` picks the pictogram over the door, `stock` names the goods
 * catalogue in items.js, and `hours` is [openHour, closeHour] on a 24h clock.
 * `days` lists weekdays the place opens (0 = Sunday).
 */
export const SHOPS = [
  {
    id: 'cafe', town: 'brambleford', name: 'Your Cat Cafe', sign: 'cafe',
    kind: 'home', tw: 5, wall: '#f5e8cc', roof: '#c86a4a', roofStyle: 'tile', awning: '#c05a7a',
    hours: [0, 24], days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'grocer', town: 'brambleford', name: "Pips' Provisions", sign: 'grocer',
    kind: 'shop', stock: 'grocer', keeper: 'pip', tw: 4, roof: '#5a6472',
    hours: [7, 19], days: [1, 2, 3, 4, 5, 6],
    greet: 'Morning! Fresh in today, and only slightly squashed.',
  },
  {
    id: 'bakery', town: 'brambleford', name: 'The Warm Loaf', sign: 'bakery',
    kind: 'shop', stock: 'bakery', keeper: 'dough', tw: 4, roof: '#d0a659', roofStyle: 'thatch', awning: '#e08b3f',
    hours: [6, 15], days: [0, 2, 3, 4, 5, 6],
    greet: 'Everything you can smell is for sale. Including the smell.',
  },
  {
    id: 'petshop', town: 'brambleford', name: 'Whisker & Paw', sign: 'pet',
    kind: 'cats', stock: 'petshop', keeper: 'marigold', tw: 5, roof: '#c86a4a',
    hours: [9, 18], days: [1, 2, 3, 4, 5, 6],
    greet: 'Come to look, or come to take somebody home?',
  },
  {
    id: 'inn', town: 'brambleford', name: 'The Sleeping Hare', sign: 'inn',
    kind: 'inn', keeper: 'hollis', tw: 5, roof: '#b2624b', timbered: true,
    storeys: 2, wallH: 54, roofH: 26,
    hours: [0, 24], days: [0, 1, 2, 3, 4, 5, 6],
    greet: 'Bed upstairs whenever you like. Mind the third stair.',
  },
  {
    id: 'groomer', town: 'hollowdown', name: 'Fluff & Tumble', sign: 'groomer',
    kind: 'groomer', keeper: 'suds', tw: 4, roof: '#7d8794', awning: '#d472b0',
    hours: [9, 17], days: [2, 3, 4, 5, 6],
    greet: 'Bring them in scruffy, take them out magnificent.',
  },
  {
    id: 'builder', town: 'hollowdown', name: "Trowel & Sons", sign: 'builder',
    kind: 'builder', keeper: 'trowel', tw: 5, roof: '#5a6472',
    hours: [7, 16], days: [1, 2, 3, 4, 5],
    greet: 'You want it built, or you want it built *well*? Different prices.',
  },
  {
    id: 'hardware', town: 'hollowdown', name: 'The Chalk Pit Store', sign: 'builder',
    kind: 'shop', stock: 'hardware', keeper: 'flint', tw: 4, roof: '#7d8794',
    hours: [8, 17], days: [1, 2, 3, 4, 5, 6],
    greet: 'Timber, tile, slate, nails. Not cats. People keep asking.',
  },
  {
    id: 'vet', town: 'saltmere', name: 'Dr. Bramble, Vet', sign: 'vet',
    kind: 'vet', keeper: 'bramble', tw: 4, roof: '#4f6a72',
    hours: [8, 18], days: [1, 2, 3, 4, 5, 6],
    greet: 'Sneezing? Sulking? Suspiciously quiet? Bring them here.',
  },
  {
    id: 'fishmonger', town: 'saltmere', name: 'Coldwater Fish', sign: 'fish',
    kind: 'shop', stock: 'fish', keeper: 'kelp', tw: 4, roof: '#7d8794',
    hours: [5, 13], days: [2, 3, 4, 5, 6],
    greet: 'Landed this morning. The cats can smell it from the hill.',
  },
  {
    id: 'harbour', town: 'saltmere', name: 'Harbour Supplies', sign: 'grocer',
    kind: 'shop', stock: 'harbour', keeper: 'anchor', tw: 4, roof: '#b2624b',
    hours: [7, 17], days: [0, 1, 2, 3, 4, 5, 6],
    greet: 'Rope, salt, tea, biscuits. In that order of importance.',
  },
  {
    id: 'furniture', town: 'thistlewick', name: 'Velvet & Oak', sign: 'furniture',
    kind: 'shop', stock: 'furniture', keeper: 'velvet', tw: 5, roof: '#b2624b', awning: '#8a72d6',
    hours: [10, 18], days: [1, 2, 3, 4, 5, 6],
    greet: 'Sit on anything you like. Except the chaise. That one bites.',
  },
  {
    id: 'flea', town: 'thistlewick', name: 'Thistlewick Flea Market', sign: 'furniture',
    kind: 'flea', keeper: 'rummage', tw: 6, roof: '#d0a659', roofStyle: 'thatch',
    hours: [8, 15], days: [0, 6],
    greet: 'Different junk every week. Some of it is even good.',
  },
  {
    id: 'teahouse', town: 'thistlewick', name: 'Steeped', sign: 'tea',
    kind: 'shop', stock: 'tea', keeper: 'oolong', tw: 4, roof: '#6b7d54', awning: '#6b9e8f',
    hours: [9, 19], days: [1, 2, 3, 4, 5, 6],
    greet: 'Forty-one varieties. I will describe them all if you let me.',
  },
  {
    id: 'exotic', town: 'thistlewick', name: 'Far Fields Cattery', sign: 'pet',
    kind: 'cats', stock: 'exotic', keeper: 'sable', tw: 5, roof: '#8a72d6',
    hours: [11, 17], days: [3, 5, 6],
    greet: 'These are not ordinary cats. The prices reflect that.',
  },
  {
    id: 'herbalist', town: 'oakhollow', name: 'Root & Remedy', sign: 'book',
    kind: 'shop', stock: 'herbalist', keeper: 'yarrow', tw: 4, roof: '#6b7d54', roofStyle: 'thatch',
    hours: [8, 18], days: [0, 1, 2, 3, 4, 5, 6],
    greet: 'Everything here was a plant this morning.',
  },
  {
    id: 'beekeeper', town: 'oakhollow', name: 'Hum & Comb', sign: 'grocer',
    kind: 'shop', stock: 'beekeeper', keeper: 'clover', tw: 3, roof: '#d0a659', roofStyle: 'thatch',
    hours: [9, 16], days: [1, 3, 5, 6],
    greet: "Don't mind the bees. They're only curious.",
  },
];

/**
 * Villagers. Species and coat are picked deterministically when omitted.
 * `lines` cycle as you talk; `hint` lines only appear once the player has
 * asked around, and often point at a shop or an item.
 */
export const VILLAGERS = [
  // --- Brambleford ---
  { id: 'pip', name: 'Pip', town: 'brambleford', species: 'mouse', coat: 'cream', role: 'grocer',
    lines: ["Everything's fresher than it looks. That's not a high bar, admittedly.",
      "Cats drink milk, cats drink cream, cats drink whatever you left out. Stock accordingly.",
      "Buy the beans in bulk. Your customers can tell, honestly."],
    hint: "If you want the really good cat food, you want fish. Saltmere. Get there before noon or Kelp sells out." },
  { id: 'dough', name: 'Dough', town: 'brambleford', species: 'bear', coat: 'bear', role: 'baker',
    lines: ["Up since four. Ask me anything, I won't remember it.",
      "A cafe with no cake is just a room with chairs.",
      "Scones on Wednesdays. Don't argue with me about scones."],
    hint: "Clover in Oakhollow keeps bees. Honey in a bake makes folk stay an hour longer, I swear it." },
  { id: 'marigold', name: 'Marigold', town: 'brambleford', species: 'rabbit', coat: 'rabbit', role: 'petshop',
    lines: ["Every cat here is looking for somebody. Take your time.",
      "A bored cat is a destructive cat. Buy toys. I'm biased, but I'm right.",
      "They'll pick you, you know. Not the other way round."],
    hint: "Sable over in Thistlewick has breeds I can't get. Only opens some days. Bring money. Bring a lot of money." },
  { id: 'hollis', name: 'Hollis', town: 'brambleford', species: 'dog', coat: 'brown', role: 'innkeeper',
    lines: ["Sleep here any time, I'll not charge a neighbour.",
      "Weekend crowds are the real test of a cafe. Be ready.",
      "There's a fellow comes through selling maps. Never has the one you want."],
    hint: "You'll want Trowel up in Hollowdown before you knock any walls about. He's grumpy. He's also the only one." },
  { id: 'nettle', name: 'Nettle', town: 'brambleford', species: 'hedgehog', coat: 'brown', role: 'villager',
    lines: ["Morning. Or afternoon. I've lost track, don't tell anyone.",
      "The pond ducks are organised. I don't like it.",
      "You're the one with the cats, aren't you? The whole lane smells of catnip."] },
  { id: 'brook', name: 'Brook', town: 'brambleford', species: 'otter', coat: 'brown', role: 'villager',
    lines: ["Water's high after the rain. Good fishing, bad boots.",
      "I swim the river to Saltmere sometimes. Faster than the road, honestly.",
      "Ever tried sitting in a cafe with wet fur? Nobody thanks you for it."] },
  { id: 'button', name: 'Button', town: 'brambleford', species: 'corgi', coat: 'ginger', role: 'villager',
    lines: ["Short legs, long opinions.",
      "I'd visit your cafe more if there were somewhere comfy to sit.",
      "Everyone says the hill town is nicer. Everyone is wrong."] },
  { id: 'thimble', name: 'Thimble', town: 'brambleford', species: 'mouse', coat: 'grey', role: 'villager',
    lines: ["Careful, I'm very small and you are very not.",
      "I count the cats when I walk past. It's my hobby. Don't judge me.",
      "Four today. There were five yesterday. I worry."] },
  { id: 'juniper', name: 'Juniper', town: 'brambleford', species: 'fox', coat: 'fox', role: 'villager',
    lines: ["Lovely spot you've got. Bit bare, though, isn't it?",
      "Plants. Pictures. A rug. It's not hard.",
      "I'd stay longer if it felt like somewhere worth staying."] },
  { id: 'pebble', name: 'Pebble', town: 'brambleford', species: 'frog', coat: 'green', role: 'villager',
    lines: ["Pond's mine. I let the ducks use it.",
      "Rain coming. My knees know.",
      "You should put a table by a window. People like windows."] },
  { id: 'moss', name: 'Moss', town: 'brambleford', species: 'sheep', coat: 'white', role: 'villager',
    lines: ["I do like a sit down.",
      "Chairs. That's my review of your establishment. More chairs.",
      "Wool's coming in nicely this year, thanks for asking."] },

  // --- Hollowdown ---
  { id: 'trowel', name: 'Trowel', town: 'hollowdown', species: 'goat', coat: 'grey', role: 'builder',
    lines: ["You want an extension. Everyone wants an extension.",
      "Money first, then workers, then walls. In that order.",
      "I can put a roof on anything. Doesn't mean I should."],
    hint: "Hire more hands and I'll let you build bigger. Simple as that." },
  { id: 'suds', name: 'Suds', town: 'hollowdown', species: 'poodle', coat: 'white', role: 'groomer',
    lines: ["A groomed cat is a cat that gets looked at. A cat that gets looked at earns you money.",
      "Wears off after a week or so. Fur doesn't stay perfect. Nothing does.",
      "Bring them all in at once and I'll do you a rate. I'm generous on Tuesdays."] },
  { id: 'flint', name: 'Flint', town: 'hollowdown', species: 'badger', coat: 'grey', role: 'hardware',
    lines: ["Slate, tile, or thatch. Thatch leaks. Slate's dear. Tile's sensible.",
      "Everything here is heavier than it looks.",
      "You'll want good timber if you're going up two rooms."] },
  { id: 'chalk', name: 'Chalk', town: 'hollowdown', species: 'squirrel', coat: 'brown', role: 'villager',
    lines: ["Mind the steps. Everyone minds the steps eventually.",
      "Built on a hill, we were. Nobody remembers why.",
      "Good view though. You can see the sea on a clear day."] },
  { id: 'wren', name: 'Wren', town: 'hollowdown', species: 'songbird', coat: 'robin', role: 'postmaster',
    lines: ["Letters! I carry letters. Anywhere in the valley, no matter the weather.",
      "Drop something in a postbox and I'll find whoever it's for.",
      "People are much braver in writing than in person. I read the outsides only, mind."],
    hint: "If a villager gives you their address, post them something. Folk remember a kindness." },
  { id: 'gorse', name: 'Gorse', town: 'hollowdown', species: 'goat', coat: 'brown', role: 'villager',
    lines: ["I eat the hedges so you don't have to.",
      "That path east has been blocked since the storm. Big rock. Very rude.",
      "Somebody strong could shift it. Not me. I have a bad knee and a good excuse."],
    hint: "The blocked path east needs proper tools. Ask at the Chalk Pit Store." },
  { id: 'tuft', name: 'Tuft', town: 'hollowdown', species: 'owl', coat: 'owl', role: 'villager',
    lines: ["Up late. Always up late.",
      "Your cafe's lovely at night. Very few people know that.",
      "Try opening in the evening sometime. Different crowd. Quieter tippers."] },
  { id: 'slate', name: 'Slate', town: 'hollowdown', species: 'raven', coat: 'raven', role: 'villager',
    lines: ["Caw. Sorry. Habit.",
      "I collect shiny things. Professionally. It's called being a merchant.",
      "There's a lighthouse down the coast nobody visits. Something's in it."] },

  // --- Saltmere ---
  { id: 'bramble', name: 'Dr. Bramble', town: 'saltmere', species: 'deer', coat: 'brown', role: 'vet',
    lines: ["Sick cat? Bring them straight in. It spreads, you know.",
      "One sneezing cat becomes three sneezing cats becomes a very quiet cafe.",
      "Prevention is cheaper than cure. Feed them properly and I'll see less of you."],
    hint: "Keep a sick cat away from the others, or bring them to me the same day. That's the whole of it." },
  { id: 'kelp', name: 'Kelp', town: 'saltmere', species: 'seal', coat: 'seal', role: 'fishmonger',
    lines: ["Fresh. Very fresh. Was swimming an hour ago.",
      "Cats know good fish. You can't fool a cat with yesterday's mackerel.",
      "Sold out by noon most days. Early bird, and so on."] },
  { id: 'anchor', name: 'Anchor', town: 'saltmere', species: 'dog', coat: 'grey', role: 'harbour',
    lines: ["Everything a boat needs and a few things it doesn't.",
      "Storm's coming in. Or it isn't. I'm not a gull.",
      "Tea from the docks is cheaper than Thistlewick. Don't tell Oolong."] },
  { id: 'shrimp', name: 'Shrimp', town: 'saltmere', species: 'otter', coat: 'brown', role: 'villager',
    lines: ["Found a lovely shell this morning. Not telling you where.",
      "The beach gives things up after a storm.",
      "Somebody said there's treasure. Somebody says that every year."] },
  { id: 'gull', name: 'Gull', town: 'saltmere', species: 'songbird', coat: 'white', role: 'villager',
    lines: ["MINE. Sorry. Reflex.",
      "You can't sit outside a cafe here. We'd have your cake off you in seconds.",
      "Nothing personal. It's a lifestyle."] },
  { id: 'marlin', name: 'Marlin', town: 'saltmere', species: 'seal', coat: 'seal', role: 'villager',
    lines: ["Water's cold. Water's always cold. That's the point of water.",
      "I sit on that rock most days. It's a good rock.",
      "Come swimming. No? Suit yourself."] },
  { id: 'cockle', name: 'Cockle', town: 'saltmere', species: 'hedgehog', coat: 'brown', role: 'villager',
    lines: ["Careful where you tread on the shingle.",
      "I do like a cafe. Somewhere out of the wind.",
      "You'll want a fireplace, up here on the coast. Trust me."] },
  { id: 'tern', name: 'Tern', town: 'saltmere', species: 'songbird', coat: 'bluebird', role: 'taxi',
    lines: ["Need a lift? I fly, you pay, everyone's happy.",
      "Anywhere you've already been. I'm not an explorer, I'm a taxi.",
      "Not after dark. I'm a bird, not an owl."] },

  // --- Thistlewick ---
  { id: 'velvet', name: 'Velvet', town: 'thistlewick', species: 'cat', coat: 'siam', role: 'furniture',
    lines: ["Comfort sells. Ugly comfort sells less. Bear that in mind.",
      "A room should say something. Yours currently says 'we ran out of money'.",
      "Buy the good sofa. You'll make it back in a fortnight."] },
  { id: 'rummage', name: 'Rummage', town: 'thistlewick', species: 'raven', coat: 'raven', role: 'flea',
    lines: ["Weekends only. Rest of the week I'm out finding this rubbish.",
      "Half price, no returns, no questions.",
      "That? That's an antique. That? That's a chair. Depends what you'll pay."] },
  { id: 'oolong', name: 'Oolong', town: 'thistlewick', species: 'rabbit', coat: 'grey', role: 'tea',
    lines: ["Water off the boil. Off. The. Boil.",
      "A good pot makes people linger. Lingering people order twice.",
      "I have a smoked one that tastes like a bonfire. Not everyone's cup. Ha."] },
  { id: 'sable', name: 'Sable', town: 'thistlewick', species: 'cat', coat: 'black', role: 'exotic',
    lines: ["My cats have papers. Longer papers than most people.",
      "Rare coats draw a crowd. That's not vanity, it's arithmetic.",
      "I only open some days. Rarity is the business."] },
  { id: 'copper', name: 'Copper', town: 'thistlewick', species: 'fox', coat: 'russet', role: 'villager',
    lines: ["Market day is the best day. Market day is the only day.",
      "I've bought three things I don't need already.",
      "Watch your purse. Not from me. From the general situation."] },
  { id: 'ledger', name: 'Ledger', town: 'thistlewick', species: 'owl', coat: 'owl', role: 'villager',
    lines: ["Business advice, free, unsolicited: know your costs.",
      "A cat eats every day whether you open or not. Did you know that? People don't.",
      "Pay staff too little and they'll cost you more than they save."],
    hint: "Once you can afford help, set a fair wage. Underpay and the customers stop coming back." },
  { id: 'primrose', name: 'Primrose', town: 'thistlewick', species: 'sheep', coat: 'cream', role: 'villager',
    lines: ["I've walked past your cafe. It looked full. I kept walking.",
      "Nobody likes queueing. Put more seats in.",
      "That's my whole point, really. More seats."] },
  { id: 'grist', name: 'Grist', town: 'thistlewick', species: 'mouse', coat: 'brown', role: 'villager',
    lines: ["Miller's family. Four generations. The mill's gone, mind.",
      "Old mill's up the river. Nobody goes. Something's still in there.",
      "Careful if you do. Floorboards."] },
  { id: 'saffron', name: 'Saffron', town: 'thistlewick', species: 'cat', coat: 'ginger', role: 'villager',
    lines: ["I'd work in a cafe. I'd be brilliant at it.",
      "Ask around when you can afford somebody. I know people. I am people.",
      "Fair wage and I'm yours."] },

  // --- Oakhollow ---
  { id: 'yarrow', name: 'Yarrow', town: 'oakhollow', species: 'deer', coat: 'brown', role: 'herbalist',
    lines: ["Catnip, chamomile, and something for that cough.",
      "Half of medicine is rest. The other half I sell in jars.",
      "A cat that eats well rarely needs me."] },
  { id: 'clover', name: 'Clover', town: 'oakhollow', species: 'bear', coat: 'brown', role: 'beekeeper',
    lines: ["Bees are doing well. Bees are always doing well or catastrophically badly.",
      "Honey in the tea. Honey on the scone. Honey in everything, really.",
      "Slow down. Nothing in these woods is in a hurry."] },
  { id: 'acorn', name: 'Acorn', town: 'oakhollow', species: 'squirrel', coat: 'ginger', role: 'villager',
    lines: ["I've hidden about four hundred of these. I remember maybe six.",
      "The big oak's older than the village. We built round it.",
      "Quiet here. That's not a complaint."] },
  { id: 'fern', name: 'Fern', town: 'oakhollow', species: 'rabbit', coat: 'brown', role: 'villager',
    lines: ["Mushrooms after rain. Only the ones you know, mind.",
      "Sometimes I walk to Brambleford just for the bread.",
      "That's an hour each way. Worth it."] },
  { id: 'hazel', name: 'Hazel', town: 'oakhollow', species: 'mouse', coat: 'brown', role: 'villager',
    lines: ["We don't get many visitors. You're a bit of an event.",
      "There's a path through the woods most people miss.",
      "Follow the mushrooms. I'm being serious."] },
  { id: 'bracken', name: 'Bracken', town: 'oakhollow', species: 'hedgehog', coat: 'brown', role: 'villager',
    lines: ["Prickles are a personality, I've decided.",
      "Someone left a lantern at the standing stones. Odd.",
      "I'd fetch it but, well. Prickles."] },

  // --- wanderers, found out on the roads ---
  { id: 'ambrose', name: 'Ambrose', town: null, species: 'dog', coat: 'brown', role: 'wanderer',
    lines: ["Walking's the thing. Never mind where to.",
      "Met a cat on this road once who could talk. Or I'd had a long day.",
      "Roads all meet up eventually. Comforting, that."] },
  { id: 'lark', name: 'Lark', town: null, species: 'songbird', coat: 'robin', role: 'wanderer',
    lines: ["Singing's free. Requests are also free. I only know the one song.",
      "Music in a cafe. Think about it.",
      "I'd play for tips and a bun."] },
  { id: 'quill', name: 'Quill', town: null, species: 'hedgehog', coat: 'grey', role: 'wanderer',
    lines: ["Writing it all down. The valley, the people, the weather.",
      "You'll be in it. Try to be interesting.",
      "So far I have four pages about a duck."] },
  { id: 'harrow', name: 'Harrow', town: null, species: 'goat', coat: 'brown', role: 'farmer',
    lines: ["Field's in. Nothing to do but worry.",
      "Milk goes to the grocer Tuesdays. Get it fresh.",
      "Cats keep the mice off. Yours are welcome any time. Don't tell the mice."] },
  { id: 'poppy', name: 'Poppy', town: null, species: 'rabbit', coat: 'white', role: 'farmer',
    lines: ["Twelve of them. Twelve! And they all want feeding.",
      "You think cats are demanding.",
      "Come by in spring, it's chaos, you'd love it."] },
  { id: 'rook', name: 'Rook', town: null, species: 'raven', coat: 'raven', role: 'wanderer',
    lines: ["Standing stones are older than anyone. Nobody knows who put them there.",
      "I sit on them. Feels important.",
      "Something under the middle one. Never dug. Wouldn't dare."] },
  { id: 'willow', name: 'Willow', town: null, species: 'deer', coat: 'cream', role: 'wanderer',
    lines: ["The river's the oldest road there is.",
      "Follow it far enough and you get to the sea.",
      "Follow it the other way and you get wet."] },
  { id: 'sorrel', name: 'Sorrel', town: null, species: 'fox', coat: 'ginger', role: 'wanderer',
    lines: ["Lost? Everyone's lost round here at first.",
      "Towns are: there, there, over that hill, and the one nobody can find.",
      "You'll find it. Or you won't. Either's fine."] },
  { id: 'birch', name: 'Birch', town: null, species: 'squirrel', coat: 'grey', role: 'wanderer',
    lines: ["Woods go on further than you'd think.",
      "I've never reached the end of them. I've tried twice.",
      "Third time's planned for spring."] },
  { id: 'peat', name: 'Peat', town: null, species: 'badger', coat: 'grey', role: 'wanderer',
    lines: ["Down there's my sett. No, you can't see it.",
      "Digging's honest work. Nobody appreciates it.",
      "If you ever need a hole, you know where I am."] },
  { id: 'meadow', name: 'Meadow', town: null, species: 'sheep', coat: 'white', role: 'farmer',
    lines: ["Grass is good this year. Really is.",
      "That's the whole update. Grass. Good.",
      "See you tomorrow, probably."] },
  { id: 'tansy', name: 'Tansy', town: null, species: 'cat', coat: 'calico', role: 'wanderer',
    lines: ["Another one on two legs! We're rarer than you'd think.",
      "Most of my cousins never bothered standing up. Their loss.",
      "A cafe full of cats. That's either genius or a fire hazard."] },
  { id: 'dill', name: 'Dill', town: null, species: 'frog', coat: 'green', role: 'wanderer',
    lines: ["Damp today. Excellent.",
      "You want to talk to the birds about the taxi thing. They're organised.",
      "Not me. I hop. It's slower but it's dignified."] },
  { id: 'ash', name: 'Ash', town: null, species: 'owl', coat: 'owl', role: 'wanderer',
    lines: ["Night's the best of it. All this, and nobody about.",
      "Lamps make a village look like a handful of coals from up here.",
      "You should light your cafe properly. It shows from the hill."] },
];

/** Generic chatter mixed into conversations to keep repeat visits alive. */
export const GOSSIP = [
  "Did you hear? The postmaster's learning the fiddle. Badly.",
  "They say the flea market had a genuine antique last week. They say that every week.",
  "Rain on the way. My whiskers know these things.",
  "Somebody left the gate open again and the sheep got into the churchyard.",
  "The baker's started doing a thing with honey. Life-changing, apparently.",
  "There's a cat up at the old mill nobody can catch.",
  "Weekends the whole valley comes out. Best day for business, worst day for peace.",
  "The hill folk think we're soft down here. They're not wrong.",
  "I heard the cattery had a cat with no fur at all. Imagine.",
  "Somebody's been leaving flowers at the standing stones.",
  "Ferry's off again. It's always off.",
  "Best tea in the valley isn't at the tea shop. Don't tell them I said so.",
  "The vet says half her callouts are cats who were only sulking.",
  "Everyone's talking about that cafe with the cats. That's you, isn't it?",
  "Warm night. The kind where nobody wants to go home.",
];

export const LANDMARKS = [
  { id: 'oldmill', name: 'The Old Mill', hint: 'A wheel that hasn\'t turned in thirty years.' },
  { id: 'stones', name: 'The Standing Stones', hint: 'Older than the towns. Nobody argues with them.' },
  { id: 'lighthouse', name: 'Gullrock Light', hint: 'Still lit. Nobody is sure by whom.' },
  { id: 'bigoak', name: 'The Great Oak', hint: 'Oakhollow was built around it, not the other way round.' },
];
