// The cast, as plain data.
//
// Written by the editor in tools/editor. Everything in here is data: no
// functions, no imports, nothing that cannot survive a round trip through
// JSON. Hand edits are welcome and will be kept, but the formatting and any
// comments outside this header are replaced the next time the editor saves.
// A prose note about a particular entry belongs in its own `note` field,
// which is data and does survive.
//
// secretMet() and arrivesNow() live in villagers.js and read the small objects here.

export const VILLAGERS = [
  {
    id: 'pip',
    name: 'Pip',
    town: 'brambleford',
    species: 'mouse',
    coat: 'cream',
    role: 'grocer',
    lines: [
      "Everything's fresher than it looks. That's not a high bar, I'll admit.",
      "Kittens drink milk, and cats eat fish, or kibble if you don't have any fish. Stock up accordingly.",
      "Some customers like the cheap coffee, and some won't drink anything but the fancy stuff, so stock accordingly.",
    ],
    hints: [
      {
        text: "If you want the really good cat food, you need fish from Saltmere. Get there before noon, or Kelp will be sold out.",
      },
    ],
  },
  {
    id: 'dough',
    name: 'Dough',
    town: 'brambleford',
    species: 'bear',
    coat: 'bear',
    role: 'baker',
    lines: [
      "I've been up since four in the morning, so don't ask me anything. I won't remember it.",
      'A cafe with no cake is just a room with chairs.',
      "I make scones on Wednesdays, and don't argue with me about scones.",
    ],
    hints: [
      {
        text: "Clover in Oakhollow keeps bees. If you put honey in your baking, people stay an hour longer. I swear it's true.",
      },
    ],
  },
  {
    id: 'marigold',
    name: 'Marigold',
    town: 'brambleford',
    species: 'rabbit',
    coat: 'rabbit',
    role: 'petshop',
    lines: [
      'Every cat here is looking for somebody. That somebody might just be you.',
      "A bored cat is a destructive cat, so buy toys. I'm biased, but I'm right.",
      "They'll pick you, you know, not the other way around.",
    ],
    hints: [
      {
        text: "Sable over in Thistlewick has breeds I can't get, but she only opens some days. Bring money. Bring a LOT of money.",
      },
    ],
  },
  {
    id: 'hollis',
    name: 'Hollis',
    town: 'brambleford',
    species: 'dog',
    coat: 'brown',
    role: 'innkeeper',
    lines: [
      "You can sleep here anytime, and I won't charge a neighbor. Don't let word get out, though, because I'm trying to run a business.",
      'Weekend crowds are the real test of a cafe. Be ready!',
      "There's a guy who comes through selling maps. He never has the one you want.",
    ],
    hints: [
      {
        text: "You'll want to hire Trowel up in Hollowdown if you want to expand the cafe. He's grumpy, but he's also the only carpenter in the valley.",
      },
    ],
  },
  {
    id: 'nettle',
    name: 'Nettle',
    town: 'brambleford',
    species: 'hedgehog',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Good morning. Or is it afternoon? I've lost track.",
      "Your grandmother was a sweet lady, and I'm glad you reopened the cafe. Cats are kind of a bold business choice, though.",
      'Cats get along with hedgehogs, right?',
    ],
  },
  {
    id: 'brook',
    name: 'Brook',
    town: 'brambleford',
    species: 'otter',
    coat: 'brown',
    role: 'villager',
    lines: [
      "The water's high after the rain. That's good for fishing, but bad for boots.",
      "I swim the river to Saltmere sometimes. Honestly, it's faster than the road.",
      'Ever tried sitting in a cafe with wet fur? Nobody thanks you for it.',
      'A cafe with a fireplace is a fine thing on a rainy day.',
    ],
  },
  {
    id: 'button',
    name: 'Button',
    town: 'brambleford',
    species: 'corgi',
    coat: 'ginger',
    role: 'villager',
    lines: [
      "I'm a corgi! I'm short on legs but, like most folks in the valley, long on opinions.",
      "I'd visit your cafe more if there were somewhere comfy to sit.",
      'Everyone says corgis are hard to live with. Everyone is wrong.',
    ],
  },
  {
    id: 'thimble',
    name: 'Thimble',
    town: 'brambleford',
    species: 'mouse',
    coat: 'grey',
    role: 'villager',
    lines: [
      "I'm a mouse! Be careful, I'm very small.",
      "I count the cats when I walk past. It's my hobby.",
      'A mouse has the right to choose their own hobby without being judged for it.',
    ],
  },
  {
    id: 'juniper',
    name: 'Juniper',
    town: 'brambleford',
    species: 'fox',
    coat: 'fox',
    role: 'villager',
    lines: [
      "You've got a nice spot here. It's kind of bare, though, isn't it?",
      "You could add some plants, some pictures, maybe a rug. It's not hard.",
      "I'd stay longer if it felt like somewhere worth staying.",
    ],
  },
  {
    id: 'pebble',
    name: 'Pebble',
    town: 'brambleford',
    species: 'frog',
    coat: 'green',
    role: 'villager',
    lines: [
      "The pond's mine, but I let the ducks use it. They won't bother anyone, I promise.",
      "Rain must be coming, because my knees can feel it.",
      "You should put a table by a window. People like windows. People don't like ducks.",
      "I'll hop on in, as long as the cats behave themselves around frogs.",
    ],
  },
  {
    id: 'moss',
    name: 'Moss',
    town: 'brambleford',
    species: 'sheep',
    coat: 'white',
    role: 'villager',
    lines: [
      'I do love a good sit-down.',
      "Here's my review of your establishment: it needs more chairs.",
      'My wool is coming in nicely this year, thanks for asking.',
    ],
  },
  {
    id: 'trowel',
    name: 'Trowel',
    town: 'hollowdown',
    species: 'goat',
    coat: 'grey',
    role: 'builder',
    lines: [
      'You want an expansion? Everyone wants to expand.',
      'Hire workers and pay for materials. Then you can build new rooms.',
      "I can put a roof on anything. That doesn't mean I should.",
    ],
    hints: [
      {
        text: "Hire more hands and I'll let you build bigger. It's as simple as that.",
      },
    ],
  },
  {
    id: 'suds',
    name: 'Suds',
    town: 'hollowdown',
    species: 'poodle',
    coat: 'white',
    role: 'groomer',
    lines: [
      'A groomed cat is a cat that gets looked at. A cat that gets looked at earns you money.',
      "Grooming wears off after a week or so. Fur doesn't stay perfect, and neither does anything else. That's entropy for you.",
      "Bring them all in at once and I'll cut you a deal. I'm generous on Tuesdays.",
    ],
  },
  {
    id: 'flint',
    name: 'Flint',
    town: 'hollowdown',
    species: 'badger',
    coat: 'grey',
    role: 'hardware',
    lines: [
      'We sell all kinds of building materials. What do you need?',
      'Everything here is heavier than it looks.',
      "You'll want good timber if you're going to build new rooms.",
    ],
  },
  {
    id: 'chalk',
    name: 'Chalk',
    town: 'hollowdown',
    species: 'squirrel',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Watch the steps. Everybody learns to watch the steps... eventually.",
      "The whole town's built on a hill. Nobody remembers why.",
      "It's a good view, though. You can see the sea on a clear day.",
    ],
  },
  {
    id: 'wren',
    name: 'Wren',
    town: 'hollowdown',
    species: 'songbird',
    coat: 'robin',
    role: 'postmaster',
    lines: [
      "Letters! I carry letters anywhere in the valley, no matter the weather.",
      "Drop something in a mailbox and I'll find whoever it's for.",
      "People are much braver in writing than in person, or so I've been told.",
    ],
    hints: [
      {
        text: 'If a villager gives you their address, mail them something. People remember a kindness.',
      },
    ],
  },
  {
    id: 'gorse',
    name: 'Gorse',
    town: 'hollowdown',
    species: 'goat',
    coat: 'brown',
    role: 'villager',
    lines: [
      "I eat the hedges so you don't have to. You're welcome!",
      "That path east has been blocked by a big rock ever since the storm. How rude of it!",
      "Somebody strong could move it, but not me. I've got a bad knee.",
    ],
    hints: [
      {
        text: "You'll need real tools for that blocked path east. Ask at the Chalk Pit Store.",
      },
    ],
  },
  {
    id: 'tuft',
    name: 'Tuft',
    town: 'hollowdown',
    species: 'owl',
    coat: 'owl',
    role: 'villager',
    lines: [
      "I'm up late. I'm always up late.",
      "Your cafe's lovely at night. Not many people know that.",
      'Try opening in the evening sometime, and add some lamps. You get a whole different crowd at night.',
    ],
  },
  {
    id: 'slate',
    name: 'Slate',
    town: 'hollowdown',
    species: 'raven',
    coat: 'raven',
    role: 'villager',
    lines: [
      "Caw caw! Sorry, that's just a habit. How do you do? It's a pleasure to make your acquaintance.",
      "I collect shiny things professionally, which is called being a merchant. Except I never want to sell any of it, so I'm still figuring out the 'making a living' part.",
      "There's a lighthouse down the coast that nobody visits. Something's in there, but it's not shiny, so I don't bother.",
    ],
  },
  {
    id: 'bramble',
    name: 'Dr. Bramble',
    town: 'saltmere',
    species: 'deer',
    coat: 'brown',
    role: 'vet',
    lines: [
      "If you've got a sick cat, bring them straight in. It spreads, you know.",
      'One sneezing cat becomes three sneezing cats, and no one wants to come to a cafe like that.',
      "Prevention's cheaper than a cure. Feed them right and they'll stay healthy.",
    ],
    hints: [
      {
        text: "Bring a sick cat to me the same day they get sick. That's the main thing. Also, the longer a cat stays sick, the more the cure costs. Sorry, that's just how modern veterinary medicine works.",
      },
    ],
  },
  {
    id: 'kelp',
    name: 'Kelp',
    town: 'saltmere',
    species: 'seal',
    coat: 'seal',
    role: 'fishmonger',
    lines: [
      "My fish are the freshest around. They were swimming in the sea an hour ago.",
      "Cats know good fish. You can't fool a cat with fish sticks.",
      "I'm sold out by noon most days. The early bird gets the worm, or in this case, the fish.",
    ],
  },
  {
    id: 'anchor',
    name: 'Anchor',
    town: 'saltmere',
    species: 'dog',
    coat: 'grey',
    role: 'harbour',
    lines: [
      "I sell everything a boat needs, and a few things it doesn't.",
      "There's a storm coming in. Or maybe there isn't. I'm not a gull.",
      "Tea's cheaper at the docks than in Thistlewick. Don't tell Oolong.",
    ],
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    town: 'saltmere',
    species: 'otter',
    coat: 'brown',
    role: 'villager',
    lines: [
      "I found a great shell this morning and gave it to my buddy Moth. I'm not sure he really wanted it, though.",
      "The beach gives things up after a storm, but never shells. There's never a shell around when you want one.",
      "Somebody said there's treasure. Somebody says that every year.",
    ],
    hints: [
      {
        text: "That big spiral shell? Moth's got it. He's a little gray guy in Brambleford who only comes out after dark to count things on the lamps.",
      },
    ],
  },
  {
    id: 'gull',
    name: 'Gull',
    town: 'saltmere',
    species: 'songbird',
    coat: 'white',
    role: 'villager',
    lines: [
      "MINE! Sorry, that's a reflex.",
      "You can't sit outside a cafe here. We'd take your croissant in seconds.",
      "It's nothing personal. It's a lifestyle.",
    ],
  },
  {
    id: 'marlin',
    name: 'Marlin',
    town: 'saltmere',
    species: 'seal',
    coat: 'seal',
    role: 'villager',
    lines: [
      "The water's cold. The water's always cold. That's the point of water.",
      "I sit on that rock most days. It's a good rock.",
      'Come swimming. No? Suit yourself.',
    ],
  },
  {
    id: 'cockle',
    name: 'Cockle',
    town: 'saltmere',
    species: 'hedgehog',
    coat: 'brown',
    role: 'villager',
    lines: [
      'Careful where you step on the pebbles.',
      "I do like a good cafe. It's somewhere to get out of the wind.",
      "You'll want a fireplace, up here on the coast. Trust me.",
    ],
  },
  {
    id: 'tern',
    name: 'Tern',
    town: 'saltmere',
    species: 'songbird',
    coat: 'bluebird',
    role: 'taxi',
    lines: [
      "Need a ride? I fly, you pay, and everyone's happy.",
      "I'll take you anywhere you've already been. I'm not an explorer, I'm a taxi.",
      "I don't fly after dark. I'm a bird, not an owl.",
    ],
  },
  {
    id: 'velvet',
    name: 'Velvet',
    town: 'thistlewick',
    species: 'cat',
    coat: 'siam',
    role: 'furniture',
    lines: [
      "Comfort sells, but ugly comfort sells less. Bear that in mind.",
      "A room should say something. Right now yours says 'we ran out of money.'",
      "Buy the good couch. You'll make it back in two weeks.",
    ],
  },
  {
    id: 'rummage',
    name: 'Rummage',
    town: 'thistlewick',
    species: 'raven',
    coat: 'raven',
    role: 'flea',
    lines: [
      "I'm only open on weekends. I spend the rest of the week out finding all this junk.",
      "Everything's half price, with no returns and no questions asked.",
      "That? That's an antique. And that? That's a chair. It depends on what you're willing to pay.",
    ],
  },
  {
    id: 'oolong',
    name: 'Oolong',
    town: 'thistlewick',
    species: 'rabbit',
    coat: 'grey',
    role: 'tea',
    lines: [
      "Always take the water off the boil. Off. The. Boil.",
      'A good pot makes people linger. Lingering people order twice.',
      "I've got a smoked tea that tastes like a bonfire. It's not everyone's cup of tea. Ha!",
    ],
  },
  {
    id: 'sable',
    name: 'Sable',
    town: 'thistlewick',
    species: 'cat',
    coat: 'black',
    role: 'exotic',
    lines: [
      "My cats have papers, and their papers are longer than most people's.",
      "Rare coats draw a crowd. That's not vanity, it's arithmetic.",
      "I only open some days, because rarity is the business.",
    ],
  },
  {
    id: 'copper',
    name: 'Copper',
    town: 'thistlewick',
    species: 'fox',
    coat: 'russet',
    role: 'villager',
    lines: [
      'Market day is the best day. Market day is the only day.',
      "I've already bought three things I don't need.",
      "Watch your purse. I don't mean because of me, I mean because of the general situation.",
    ],
  },
  {
    id: 'ledger',
    name: 'Ledger',
    town: 'thistlewick',
    species: 'owl',
    coat: 'owl',
    role: 'villager',
    lines: [
      "Here's some free, unsolicited business advice: know your costs.",
      "A cat eats every day whether you open or not. Did you know that? People don't.",
      "Pay staff too little and they'll cost you more than they save.",
    ],
    hints: [
      {
        text: "Once you can afford help, set a fair wage. If you underpay, the customers stop coming back.",
      },
    ],
  },
  {
    id: 'primrose',
    name: 'Primrose',
    town: 'thistlewick',
    species: 'sheep',
    coat: 'cream',
    role: 'villager',
    lines: [
      "I walked past your cafe, but it looked full, so I kept walking.",
      "Nobody likes waiting in line, so put in more seats.",
      "That's my whole point, really: more seats.",
    ],
  },
  {
    id: 'grist',
    name: 'Grist',
    town: 'thistlewick',
    species: 'mouse',
    coat: 'brown',
    role: 'villager',
    lines: [
      "We were a family of millers for four generations. The mill's closed now, though.",
      "The old mill's up the river. Nobody goes there anymore, but something's still in there.",
      "Be careful if you do go, and watch the floorboards.",
    ],
  },
  {
    id: 'saffron',
    name: 'Saffron',
    town: 'thistlewick',
    species: 'cat',
    coat: 'ginger',
    role: 'villager',
    lines: [
      "I'd work in a cafe. I'd be brilliant at it.",
      'Ask around when you can afford somebody. I know people. I am people.',
      "Pay me a fair wage and I'm yours.",
    ],
  },
  {
    id: 'yarrow',
    name: 'Yarrow',
    town: 'oakhollow',
    species: 'deer',
    coat: 'brown',
    role: 'herbalist',
    lines: [
      "I've got catnip, chamomile, and something for that cough.",
      'Half of medicine is rest. The other half I sell in jars.',
      'A cat that eats well rarely needs me.',
    ],
  },
  {
    id: 'clover',
    name: 'Clover',
    town: 'oakhollow',
    species: 'bear',
    coat: 'brown',
    role: 'beekeeper',
    lines: [
      "The bees are doing well. Bees are always either doing well or doing catastrophically badly.",
      "I put honey in the tea, honey on the scones, and honey in everything, really.",
      'Slow down. Nothing in these woods is in a hurry.',
    ],
  },
  {
    id: 'acorn',
    name: 'Acorn',
    town: 'oakhollow',
    species: 'squirrel',
    coat: 'ginger',
    role: 'villager',
    lines: [
      "I've hidden about four hundred of these. I remember maybe six.",
      "The big oak's older than the village. We built around it.",
      "It's quiet here. That's not a complaint.",
    ],
  },
  {
    id: 'fern',
    name: 'Fern',
    town: 'oakhollow',
    species: 'rabbit',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Mushrooms come up after the rain, but only pick the ones you know.",
      'Sometimes I walk to Brambleford just for the bread.',
      "That's an hour each way, but it's worth it.",
    ],
  },
  {
    id: 'hazel',
    name: 'Hazel',
    town: 'oakhollow',
    species: 'mouse',
    coat: 'brown',
    role: 'villager',
    lines: [
      "We don't get many visitors. You're a bit of an event.",
      "There's a path through the woods most people miss.",
      "Follow the mushrooms. I'm being serious.",
    ],
  },
  {
    id: 'bracken',
    name: 'Bracken',
    town: 'oakhollow',
    species: 'hedgehog',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Prickles are a personality, I've decided.",
      "Someone left a lantern at the standing stones. That's odd.",
      "I'd fetch it, but it's hard to carry things when you're covered in prickles.",
    ],
  },
  {
    id: 'ambrose',
    name: 'Ambrose',
    town: null,
    species: 'dog',
    coat: 'brown',
    role: 'wanderer',
    lines: [
      "For me, it's all about the walk, not where I'm going.",
      "I met a cat on this road once who could talk. Or maybe I'd just had a long day.",
      "Roads all meet up eventually. That's comforting.",
    ],
  },
  {
    id: 'lark',
    name: 'Lark',
    town: null,
    species: 'songbird',
    coat: 'robin',
    role: 'wanderer',
    lines: [
      "Singing's free, and requests are free too. I only know the one song, though.",
      "You should think about having music in your cafe.",
      "I'd play for tips and a bun.",
    ],
  },
  {
    id: 'quill',
    name: 'Quill',
    town: null,
    species: 'hedgehog',
    coat: 'grey',
    role: 'wanderer',
    lines: [
      "I'm writing it all down: the valley, the people, the weather.",
      "You'll be in it. Try to be interesting.",
      "So far I've got four pages about a duck.",
    ],
  },
  {
    id: 'harrow',
    name: 'Harrow',
    town: null,
    species: 'goat',
    coat: 'brown',
    role: 'farmer',
    lines: [
      "The field's planted, so now there's nothing to do but worry.",
      "My milk goes to the grocer on Tuesdays, so that's when to get it fresh.",
      "Cats keep the mice away, so yours are welcome anytime. Don't tell the mice.",
    ],
  },
  {
    id: 'poppy',
    name: 'Poppy',
    town: null,
    species: 'rabbit',
    coat: 'white',
    role: 'farmer',
    lines: [
      "I've got twelve of them. Twelve! And they all need feeding.",
      "And you think cats are demanding!",
      "Come by in the spring. It's chaos, and you'd love it.",
    ],
  },
  {
    id: 'rook',
    name: 'Rook',
    town: null,
    species: 'raven',
    coat: 'raven',
    role: 'wanderer',
    lines: [
      "The standing stones are older than anyone. Nobody knows who put them there.",
      "I sit on them. It feels important.",
      "There's something under the middle one. I've never dug for it, and I wouldn't dare.",
    ],
  },
  {
    id: 'willow',
    name: 'Willow',
    town: null,
    species: 'deer',
    coat: 'cream',
    role: 'wanderer',
    lines: [
      "The river's the oldest road there is.",
      'Follow it far enough and you get to the sea.',
      'Follow it the other way and you get wet.',
    ],
  },
  {
    id: 'sorrel',
    name: 'Sorrel',
    town: null,
    species: 'fox',
    coat: 'ginger',
    role: 'wanderer',
    lines: [
      "Lost? Everyone's lost around here at first.",
      "The towns are over there, over there, over that hill, and then there's the one nobody can find.",
      "You'll find it, or you won't. Either's fine.",
    ],
  },
  {
    id: 'birch',
    name: 'Birch',
    town: null,
    species: 'squirrel',
    coat: 'grey',
    role: 'wanderer',
    lines: [
      "The woods go on further than you'd think.",
      "I've never reached the end of them. I've tried twice.",
      "I'm planning my third try for the spring.",
    ],
  },
  {
    id: 'peat',
    name: 'Peat',
    town: null,
    species: 'badger',
    coat: 'grey',
    role: 'wanderer',
    lines: [
      "My burrow's down there. No, you can't see it.",
      "Digging's honest work, but nobody appreciates it.",
      'If you ever need a hole, you know where I am.',
    ],
  },
  {
    id: 'meadow',
    name: 'Meadow',
    town: null,
    species: 'sheep',
    coat: 'white',
    role: 'farmer',
    lines: [
      "The grass is good this year. It really is.",
      "That's the whole update: the grass is good.",
      "I'll see you tomorrow, probably.",
    ],
  },
  {
    id: 'tansy',
    name: 'Tansy',
    town: null,
    species: 'cat',
    coat: 'calico',
    role: 'wanderer',
    lines: [
      "Another one on two legs! We're rarer than you'd think.",
      "Most of my cousins never bothered standing up. That's their loss.",
      "A cafe full of cats is either genius or a fire hazard.",
    ],
  },
  {
    id: 'dill',
    name: 'Dill',
    town: null,
    species: 'frog',
    coat: 'green',
    role: 'wanderer',
    lines: [
      "It's damp today. Excellent!",
      "Talk to the birds if you want a taxi. They're organized.",
      "Not me, though. I hop. It's slower, but it's dignified.",
    ],
  },
  {
    id: 'ash',
    name: 'Ash',
    town: null,
    species: 'owl',
    coat: 'owl',
    role: 'wanderer',
    lines: [
      "Night's the best part. You get all this, and there's nobody around.",
      "From up here, the lamps make a village look like a handful of coals.",
      'You should really light up your cafe. You can see it from the hill.',
    ],
  },
  {
    id: 'quire',
    name: 'Quire',
    town: 'brambleford',
    species: 'owl',
    coat: 'owl',
    role: 'library',
    when: 'always',
    lines: [
      "Shhh. Well — there's nobody else here, so talk as loud as you like.",
      "Everything ever written about this valley is on that middle shelf. It's not a long shelf.",
      "People think a library is about books, but it's really about knowing which book.",
    ],
    hints: [
      {
        text: "For anything old around here, you want the town history. It's on the middle shelf, with a green spine and gold letters.",
      },
    ],
  },
  {
    id: 'moth',
    name: 'Moth',
    town: 'brambleford',
    species: 'mouse',
    coat: 'grey',
    role: 'villager',
    when: 'night',
    lines: [
      "Don't mind me. I'm counting.",
      "I counted fourteen species on that one lamp last night. Fourteen!",
      "Everyone's asleep, and they're missing all of it.",
    ],
  },
  {
    id: 'pike',
    name: 'Pike',
    town: 'brambleford',
    species: 'hedgehog',
    coat: 'grey',
    role: 'villager',
    when: 'night',
    lines: [
      "I keep the night watch. Nobody asked me to, but nobody's complained, either.",
      "It's quiet tonight. Quiet's good, because quiet means the job's going well.",
      "Be careful down by the hedges after midnight. No reason.",
    ],
  },
  {
    id: 'woofers',
    name: 'Sir Woofers',
    town: 'brambleford',
    species: 'dog',
    coat: 'white',
    cloth: '#a8c8e8',
    role: 'ghost',
    note: 'Nobody sees him until they have looked in the hedge and told Button what they saw. A ghost dog ambling up the lane every night in plain view is not something anybody needs to discover.',
    when: 'night',
    spot: 'bushes',
    ghost: true,
    secret: { quest: 'lane_end_hedge', step: 1 },
    lines: [
      '*an extremely old dog, made mostly of moonlight, snuffling along the hedge*',
      "I've lost something. I've been losing it for a very long time.",
      "It was gold, and it was mine. They put my name on it.",
    ],
  },
  {
    id: 'vesper',
    name: 'Vesper',
    town: 'hollowdown',
    species: 'raven',
    coat: 'raven',
    role: 'villager',
    when: 'night',
    lines: [
      "This is the best view in the valley, and it only opens at night.",
      'You can see every lit window from up here. I know whose is whose.',
      "Stars are other people's lamps. That isn't true, but I like saying it.",
    ],
    hints: [
      {
        text: "Stand in the middle of the standing stones after dark. Just stand there, and you'll see.",
      },
    ],
  },
  {
    id: 'tallow',
    name: 'Tallow',
    town: 'thistlewick',
    species: 'goat',
    coat: 'cream',
    role: 'villager',
    when: 'night',
    lines: [
      'Wax sets better in the cold, so I work in the cold.',
      "I made every candle in the valley. You're welcome.",
      "A lit window is an invitation, so put one in that cafe of yours.",
    ],
  },
  {
    id: 'brine',
    name: 'Brine',
    town: 'saltmere',
    species: 'otter',
    coat: 'brown',
    role: 'villager',
    when: 'night',
    lines: [
      "Night fishing gets you a better catch but worse company. Present company excepted, of course.",
      "That old pier's rotten through. Watch your step if you go out on it.",
      "The tide takes things out and brings other things back, but never the same things.",
    ],
    hints: [
      {
        text: "Anything lost off the end of that pier is still under it. The mud keeps whatever it's given.",
      },
    ],
  },
  {
    id: 'bruin',
    name: 'Bruin',
    species: 'bear',
    coat: 'white',
    role: 'villager',
    when: 'night',
    regular: true,
    seat: 'barStool',
    lines: [
      "I don't wait in line. Lines are for people with somewhere to be.",
      "What do you call a raven who works nights? A crow-nological anomaly. ...You laughed, just slightly.",
      "A pun is a small unkindness you do to a word, and the word forgives you. Usually.",
      "There's a warm room, there are cats, and there's somebody who'll listen. I've made worse decisions than coming here.",
    ],
    hints: [
      {
        text: "There's a contest called Longest Face Wins. Whoever hears the most puns without laughing wins. I haven't won in four years, and I intend to lose again in style.",
      },
    ],
  },
  {
    id: 'comfrey',
    name: 'Comfrey',
    species: 'goat',
    coat: 'cream',
    role: 'villager',
    regular: true,
    tellsFirst: true,
    arrives: { deliveries: 10, until: 'heard_hint_comfrey' },
    lines: [
      "You're on that road so often, I've seen more of you than of the road.",
      "There's a faster way to get around this valley, and it's got fur.",
      'Ask for Bell. Everyone in Thistlewick knows Bell.',
    ],
    hints: [
      {
        text: "You're wearing that road out. Drover Bell is in Thistlewick with a riding bear for sale, and she's by the market during daylight hours. The bear's not cheap, but she's worth it.",
      },
    ],
  },
  {
    id: 'bell',
    name: 'Drover Bell',
    town: 'thistlewick',
    species: 'badger',
    coat: 'badger',
    role: 'villager',
    note: 'Not standing about in the market until somebody has told you she exists: a bear for sale is not something you walk past and fail to notice.',
    sells: 'bear',
    secret: { flag: 'heard_hint_comfrey' },
    lines: [
      "She's not a horse. Don't ride her like a horse.",
      "She eats one fresh fish a day. She'll let you know if you forget, and you won't enjoy it.",
      "Water doesn't stop her. Not much does.",
    ],
    sold: [
      "She's yours. Feed her and she'll take you anywhere.",
      "How's she doing? Is she eating? Good. That's all there is to it.",
    ],
  },
  {
    id: 'fennel',
    name: 'Fennel',
    species: 'rabbit',
    coat: 'cream',
    role: 'villager',
    regular: true,
    visitChance: 0.45,
    seat: 'stool',
    lines: [
      "I'm a man of many words and many friends. I'm back from wandering the countryside, and I've got a hankering to wet my whistle with a cordial, please.",
      "Do you have the cordial? You don't have the cordial. That's fine. I'll wait.",
      "I could go get it myself, yes. I could. But my feet are weary from my wanderings. Stock the cordial and I'll be a customer for life.",
      '*settles into the nearest chair with the finality of a dropped sandbag*',
    ],
    hints: [
      {
        text: "Go to Root & Remedy in Oakhollow. Ask for the cordial, and don't let them talk you into the tea.",
      },
    ],
  },
  {
    id: 'linnet',
    name: 'Linnet',
    species: 'deer',
    coat: 'brown',
    role: 'villager',
    when: 'night',
    regular: true,
    visitChance: 0.42,
    seat: 'barStool',
    lines: [
      "I come for the gray one. I'm not going to pretend I don't.",
      "She used to sit with me every night, in the same chair. Then she stopped.",
      "I haven't done anything. I've gone over it again and again.",
      "It's a nice room. It would be a nicer room with her in it.",
    ],
  },
  {
    id: 'pim',
    name: 'Pim',
    town: 'saltmere',
    species: 'owl',
    coat: 'owl',
    role: 'villager',
    when: 'night',
    lines: [
      "There's someone I keep meaning to talk to. I keep meaning it very hard.",
      'The trouble is, they all look the same to me. No — that came out wrong. I mean the birds.',
      "I've been rehearsing an opening line for eleven months. It's not a good one.",
    ],
  },
  {
    id: 'nutmeg',
    name: 'Nutmeg',
    town: 'thistlewick',
    species: 'mouse',
    coat: 'brown',
    role: 'villager',
    when: 'night',
    lines: [
      "I've got a job at the mill. It mostly involves being at the mill.",
      "I'll have warm milk. That's always my order, so don't make me look at the board.",
      "*asleep, upright, with the composure of someone who's had a lot of practice*",
    ],
    hints: [
      {
        text: "A cafe that's warm at two in the morning would be the finest thing in the valley, I think.",
      },
    ],
  },
  {
    id: 'nightjar',
    name: 'Nightjar',
    species: 'songbird',
    coat: 'grey',
    role: 'wanderer',
    when: 'night',
    lines: [
      '*a long whirring churr, somewhere between a bird and a distant engine*',
      "You're a long way from your lamp.",
      "I go where it's dark. That's most places, if you're patient.",
    ],
  },
];
