// The cast, as plain data.
//
// Written by the editor in tools/editor. Everything in here is data: no
// functions, no imports, nothing that cannot survive a round trip through
// JSON. Hand edits are welcome and will be kept, but the formatting and any
// comments outside this header are replaced the next time the editor saves.
// A prose note about a particular entry belongs in its own `note` field,
// which is data and does survive.
//
// secretMet() and arrivesNow() live in villagers.js and read the small objects here.

export const VILLAGERS = [
  {
    id: 'pip',
    name: 'Pip',
    town: 'brambleford',
    species: 'mouse',
    coat: 'cream',
    role: 'grocer',
    lines: [
      "Everything's fresher than it looks. That's not a high bar, admittedly.",
      'Cats drink milk, cats drink cream, cats drink whatever you left out. Stock accordingly.',
      'Buy the beans in bulk. Your customers can tell, honestly.',
    ],
    hint: 'If you want the really good cat food, you want fish. Saltmere. Get there before noon or Kelp sells out.',
  },
  {
    id: 'dough',
    name: 'Dough',
    town: 'brambleford',
    species: 'bear',
    coat: 'bear',
    role: 'baker',
    lines: [
      "Up since four. Ask me anything, I won't remember it.",
      'A cafe with no cake is just a room with chairs.',
      "Scones on Wednesdays. Don't argue with me about scones.",
    ],
    hint: 'Clover in Oakhollow keeps bees. Honey in a bake makes folk stay an hour longer, I swear it.',
  },
  {
    id: 'marigold',
    name: 'Marigold',
    town: 'brambleford',
    species: 'rabbit',
    coat: 'rabbit',
    role: 'petshop',
    lines: [
      'Every cat here is looking for somebody. Take your time.',
      "A bored cat is a destructive cat. Buy toys. I'm biased, but I'm right.",
      "They'll pick you, you know. Not the other way round.",
    ],
    hint: "Sable over in Thistlewick has breeds I can't get. Only opens some days. Bring money. Bring a lot of money.",
  },
  {
    id: 'hollis',
    name: 'Hollis',
    town: 'brambleford',
    species: 'dog',
    coat: 'brown',
    role: 'innkeeper',
    lines: [
      "Sleep here any time, I'll not charge a neighbour.",
      'Weekend crowds are the real test of a cafe. Be ready.',
      "There's a fellow comes through selling maps. Never has the one you want.",
    ],
    hint: "You'll want Trowel up in Hollowdown before you knock any walls about. He's grumpy. He's also the only one.",
  },
  {
    id: 'nettle',
    name: 'Nettle',
    town: 'brambleford',
    species: 'hedgehog',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Morning. Or afternoon. I've lost track, don't tell anyone.",
      "The pond ducks are organised. I don't like it.",
      "You're the one with the cats, aren't you? The whole lane smells of catnip.",
    ],
  },
  {
    id: 'brook',
    name: 'Brook',
    town: 'brambleford',
    species: 'otter',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Water's high after the rain. Good fishing, bad boots.",
      'I swim the river to Saltmere sometimes. Faster than the road, honestly.',
      'Ever tried sitting in a cafe with wet fur? Nobody thanks you for it.',
    ],
  },
  {
    id: 'button',
    name: 'Button',
    town: 'brambleford',
    species: 'corgi',
    coat: 'ginger',
    role: 'villager',
    lines: [
      'Short legs, long opinions.',
      "I'd visit your cafe more if there were somewhere comfy to sit.",
      'Everyone says the hill town is nicer. Everyone is wrong.',
    ],
  },
  {
    id: 'thimble',
    name: 'Thimble',
    town: 'brambleford',
    species: 'mouse',
    coat: 'grey',
    role: 'villager',
    lines: [
      "Careful, I'm very small and you are very not.",
      "I count the cats when I walk past. It's my hobby. Don't judge me.",
      'Four today. There were five yesterday. I worry.',
    ],
  },
  {
    id: 'juniper',
    name: 'Juniper',
    town: 'brambleford',
    species: 'fox',
    coat: 'fox',
    role: 'villager',
    lines: [
      "Lovely spot you've got. Bit bare, though, isn't it?",
      "Plants. Pictures. A rug. It's not hard.",
      "I'd stay longer if it felt like somewhere worth staying.",
    ],
  },
  {
    id: 'pebble',
    name: 'Pebble',
    town: 'brambleford',
    species: 'frog',
    coat: 'green',
    role: 'villager',
    lines: [
      "Pond's mine. I let the ducks use it.",
      'Rain coming. My knees know.',
      'You should put a table by a window. People like windows.',
    ],
  },
  {
    id: 'moss',
    name: 'Moss',
    town: 'brambleford',
    species: 'sheep',
    coat: 'white',
    role: 'villager',
    lines: [
      'I do like a sit down.',
      "Chairs. That's my review of your establishment. More chairs.",
      "Wool's coming in nicely this year, thanks for asking.",
    ],
  },
  {
    id: 'trowel',
    name: 'Trowel',
    town: 'hollowdown',
    species: 'goat',
    coat: 'grey',
    role: 'builder',
    lines: [
      'You want an extension. Everyone wants an extension.',
      'Money first, then workers, then walls. In that order.',
      "I can put a roof on anything. Doesn't mean I should.",
    ],
    hint: "Hire more hands and I'll let you build bigger. Simple as that.",
  },
  {
    id: 'suds',
    name: 'Suds',
    town: 'hollowdown',
    species: 'poodle',
    coat: 'white',
    role: 'groomer',
    lines: [
      'A groomed cat is a cat that gets looked at. A cat that gets looked at earns you money.',
      "Wears off after a week or so. Fur doesn't stay perfect. Nothing does.",
      "Bring them all in at once and I'll do you a rate. I'm generous on Tuesdays.",
    ],
  },
  {
    id: 'flint',
    name: 'Flint',
    town: 'hollowdown',
    species: 'badger',
    coat: 'grey',
    role: 'hardware',
    lines: [
      "Slate, tile, or thatch. Thatch leaks. Slate's dear. Tile's sensible.",
      'Everything here is heavier than it looks.',
      "You'll want good timber if you're going up two rooms.",
    ],
  },
  {
    id: 'chalk',
    name: 'Chalk',
    town: 'hollowdown',
    species: 'squirrel',
    coat: 'brown',
    role: 'villager',
    lines: [
      'Mind the steps. Everyone minds the steps eventually.',
      'Built on a hill, we were. Nobody remembers why.',
      'Good view though. You can see the sea on a clear day.',
    ],
  },
  {
    id: 'wren',
    name: 'Wren',
    town: 'hollowdown',
    species: 'songbird',
    coat: 'robin',
    role: 'postmaster',
    lines: [
      'Letters! I carry letters. Anywhere in the valley, no matter the weather.',
      "Drop something in a postbox and I'll find whoever it's for.",
      'People are much braver in writing than in person. I read the outsides only, mind.',
    ],
    hint: 'If a villager gives you their address, post them something. Folk remember a kindness.',
  },
  {
    id: 'gorse',
    name: 'Gorse',
    town: 'hollowdown',
    species: 'goat',
    coat: 'brown',
    role: 'villager',
    lines: [
      "I eat the hedges so you don't have to.",
      'That path east has been blocked since the storm. Big rock. Very rude.',
      'Somebody strong could shift it. Not me. I have a bad knee and a good excuse.',
    ],
    hint: 'The blocked path east needs proper tools. Ask at the Chalk Pit Store.',
  },
  {
    id: 'tuft',
    name: 'Tuft',
    town: 'hollowdown',
    species: 'owl',
    coat: 'owl',
    role: 'villager',
    lines: [
      'Up late. Always up late.',
      "Your cafe's lovely at night. Very few people know that.",
      'Try opening in the evening sometime. Different crowd. Quieter tippers.',
    ],
  },
  {
    id: 'slate',
    name: 'Slate',
    town: 'hollowdown',
    species: 'raven',
    coat: 'raven',
    role: 'villager',
    lines: [
      'Caw. Sorry. Habit.',
      "I collect shiny things. Professionally. It's called being a merchant.",
      "There's a lighthouse down the coast nobody visits. Something's in it.",
    ],
  },
  {
    id: 'bramble',
    name: 'Dr. Bramble',
    town: 'saltmere',
    species: 'deer',
    coat: 'brown',
    role: 'vet',
    lines: [
      'Sick cat? Bring them straight in. It spreads, you know.',
      'One sneezing cat becomes three sneezing cats becomes a very quiet cafe.',
      "Prevention is cheaper than cure. Feed them properly and I'll see less of you.",
    ],
    hint: "Keep a sick cat away from the others, or bring them to me the same day. That's the whole of it.",
  },
  {
    id: 'kelp',
    name: 'Kelp',
    town: 'saltmere',
    species: 'seal',
    coat: 'seal',
    role: 'fishmonger',
    lines: [
      'Fresh. Very fresh. Was swimming an hour ago.',
      "Cats know good fish. You can't fool a cat with yesterday's mackerel.",
      'Sold out by noon most days. Early bird, and so on.',
    ],
  },
  {
    id: 'anchor',
    name: 'Anchor',
    town: 'saltmere',
    species: 'dog',
    coat: 'grey',
    role: 'harbour',
    lines: [
      "Everything a boat needs and a few things it doesn't.",
      "Storm's coming in. Or it isn't. I'm not a gull.",
      "Tea from the docks is cheaper than Thistlewick. Don't tell Oolong.",
    ],
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    town: 'saltmere',
    species: 'otter',
    coat: 'brown',
    role: 'villager',
    lines: [
      'Found a lovely shell this morning. Gave it to my mate Moth. Not sure he really wanted it, mind.',
      'The beach gives things up after a storm. Not shells, though. Never shells when you want one.',
      "Somebody said there's treasure. Somebody says that every year.",
    ],
    hint: "That big spiral shell? Moth's got it. Little grey fellow in Brambleford — only out after dark, counting things on the lamps.",
  },
  {
    id: 'gull',
    name: 'Gull',
    town: 'saltmere',
    species: 'songbird',
    coat: 'white',
    role: 'villager',
    lines: [
      'MINE. Sorry. Reflex.',
      "You can't sit outside a cafe here. We'd have your cake off you in seconds.",
      "Nothing personal. It's a lifestyle.",
    ],
  },
  {
    id: 'marlin',
    name: 'Marlin',
    town: 'saltmere',
    species: 'seal',
    coat: 'seal',
    role: 'villager',
    lines: [
      "Water's cold. Water's always cold. That's the point of water.",
      "I sit on that rock most days. It's a good rock.",
      'Come swimming. No? Suit yourself.',
    ],
  },
  {
    id: 'cockle',
    name: 'Cockle',
    town: 'saltmere',
    species: 'hedgehog',
    coat: 'brown',
    role: 'villager',
    lines: [
      'Careful where you tread on the shingle.',
      'I do like a cafe. Somewhere out of the wind.',
      "You'll want a fireplace, up here on the coast. Trust me.",
    ],
  },
  {
    id: 'tern',
    name: 'Tern',
    town: 'saltmere',
    species: 'songbird',
    coat: 'bluebird',
    role: 'taxi',
    lines: [
      "Need a lift? I fly, you pay, everyone's happy.",
      "Anywhere you've already been. I'm not an explorer, I'm a taxi.",
      "Not after dark. I'm a bird, not an owl.",
    ],
  },
  {
    id: 'velvet',
    name: 'Velvet',
    town: 'thistlewick',
    species: 'cat',
    coat: 'siam',
    role: 'furniture',
    lines: [
      'Comfort sells. Ugly comfort sells less. Bear that in mind.',
      "A room should say something. Yours currently says 'we ran out of money'.",
      "Buy the good sofa. You'll make it back in a fortnight.",
    ],
  },
  {
    id: 'rummage',
    name: 'Rummage',
    town: 'thistlewick',
    species: 'raven',
    coat: 'raven',
    role: 'flea',
    lines: [
      "Weekends only. Rest of the week I'm out finding this rubbish.",
      'Half price, no returns, no questions.',
      "That? That's an antique. That? That's a chair. Depends what you'll pay.",
    ],
  },
  {
    id: 'oolong',
    name: 'Oolong',
    town: 'thistlewick',
    species: 'rabbit',
    coat: 'grey',
    role: 'tea',
    lines: [
      'Water off the boil. Off. The. Boil.',
      'A good pot makes people linger. Lingering people order twice.',
      "I have a smoked one that tastes like a bonfire. Not everyone's cup. Ha.",
    ],
  },
  {
    id: 'sable',
    name: 'Sable',
    town: 'thistlewick',
    species: 'cat',
    coat: 'black',
    role: 'exotic',
    lines: [
      'My cats have papers. Longer papers than most people.',
      "Rare coats draw a crowd. That's not vanity, it's arithmetic.",
      'I only open some days. Rarity is the business.',
    ],
  },
  {
    id: 'copper',
    name: 'Copper',
    town: 'thistlewick',
    species: 'fox',
    coat: 'russet',
    role: 'villager',
    lines: [
      'Market day is the best day. Market day is the only day.',
      "I've bought three things I don't need already.",
      'Watch your purse. Not from me. From the general situation.',
    ],
  },
  {
    id: 'ledger',
    name: 'Ledger',
    town: 'thistlewick',
    species: 'owl',
    coat: 'owl',
    role: 'villager',
    lines: [
      'Business advice, free, unsolicited: know your costs.',
      "A cat eats every day whether you open or not. Did you know that? People don't.",
      "Pay staff too little and they'll cost you more than they save.",
    ],
    hint: 'Once you can afford help, set a fair wage. Underpay and the customers stop coming back.',
  },
  {
    id: 'primrose',
    name: 'Primrose',
    town: 'thistlewick',
    species: 'sheep',
    coat: 'cream',
    role: 'villager',
    lines: [
      "I've walked past your cafe. It looked full. I kept walking.",
      'Nobody likes queueing. Put more seats in.',
      "That's my whole point, really. More seats.",
    ],
  },
  {
    id: 'grist',
    name: 'Grist',
    town: 'thistlewick',
    species: 'mouse',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Miller's family. Four generations. The mill's gone, mind.",
      "Old mill's up the river. Nobody goes. Something's still in there.",
      'Careful if you do. Floorboards.',
    ],
  },
  {
    id: 'saffron',
    name: 'Saffron',
    town: 'thistlewick',
    species: 'cat',
    coat: 'ginger',
    role: 'villager',
    lines: [
      "I'd work in a cafe. I'd be brilliant at it.",
      'Ask around when you can afford somebody. I know people. I am people.',
      "Fair wage and I'm yours.",
    ],
  },
  {
    id: 'yarrow',
    name: 'Yarrow',
    town: 'oakhollow',
    species: 'deer',
    coat: 'brown',
    role: 'herbalist',
    lines: [
      'Catnip, chamomile, and something for that cough.',
      'Half of medicine is rest. The other half I sell in jars.',
      'A cat that eats well rarely needs me.',
    ],
  },
  {
    id: 'clover',
    name: 'Clover',
    town: 'oakhollow',
    species: 'bear',
    coat: 'brown',
    role: 'beekeeper',
    lines: [
      'Bees are doing well. Bees are always doing well or catastrophically badly.',
      'Honey in the tea. Honey on the scone. Honey in everything, really.',
      'Slow down. Nothing in these woods is in a hurry.',
    ],
  },
  {
    id: 'acorn',
    name: 'Acorn',
    town: 'oakhollow',
    species: 'squirrel',
    coat: 'ginger',
    role: 'villager',
    lines: [
      "I've hidden about four hundred of these. I remember maybe six.",
      "The big oak's older than the village. We built round it.",
      "Quiet here. That's not a complaint.",
    ],
  },
  {
    id: 'fern',
    name: 'Fern',
    town: 'oakhollow',
    species: 'rabbit',
    coat: 'brown',
    role: 'villager',
    lines: [
      'Mushrooms after rain. Only the ones you know, mind.',
      'Sometimes I walk to Brambleford just for the bread.',
      "That's an hour each way. Worth it.",
    ],
  },
  {
    id: 'hazel',
    name: 'Hazel',
    town: 'oakhollow',
    species: 'mouse',
    coat: 'brown',
    role: 'villager',
    lines: [
      "We don't get many visitors. You're a bit of an event.",
      "There's a path through the woods most people miss.",
      "Follow the mushrooms. I'm being serious.",
    ],
  },
  {
    id: 'bracken',
    name: 'Bracken',
    town: 'oakhollow',
    species: 'hedgehog',
    coat: 'brown',
    role: 'villager',
    lines: [
      "Prickles are a personality, I've decided.",
      'Someone left a lantern at the standing stones. Odd.',
      "I'd fetch it but, well. Prickles.",
    ],
  },
  {
    id: 'ambrose',
    name: 'Ambrose',
    town: null,
    species: 'dog',
    coat: 'brown',
    role: 'wanderer',
    lines: [
      "Walking's the thing. Never mind where to.",
      "Met a cat on this road once who could talk. Or I'd had a long day.",
      'Roads all meet up eventually. Comforting, that.',
    ],
  },
  {
    id: 'lark',
    name: 'Lark',
    town: null,
    species: 'songbird',
    coat: 'robin',
    role: 'wanderer',
    lines: [
      "Singing's free. Requests are also free. I only know the one song.",
      'Music in a cafe. Think about it.',
      "I'd play for tips and a bun.",
    ],
  },
  {
    id: 'quill',
    name: 'Quill',
    town: null,
    species: 'hedgehog',
    coat: 'grey',
    role: 'wanderer',
    lines: [
      'Writing it all down. The valley, the people, the weather.',
      "You'll be in it. Try to be interesting.",
      'So far I have four pages about a duck.',
    ],
  },
  {
    id: 'harrow',
    name: 'Harrow',
    town: null,
    species: 'goat',
    coat: 'brown',
    role: 'farmer',
    lines: [
      "Field's in. Nothing to do but worry.",
      'Milk goes to the grocer Tuesdays. Get it fresh.',
      "Cats keep the mice off. Yours are welcome any time. Don't tell the mice.",
    ],
  },
  {
    id: 'poppy',
    name: 'Poppy',
    town: null,
    species: 'rabbit',
    coat: 'white',
    role: 'farmer',
    lines: [
      'Twelve of them. Twelve! And they all want feeding.',
      'You think cats are demanding.',
      "Come by in spring, it's chaos, you'd love it.",
    ],
  },
  {
    id: 'rook',
    name: 'Rook',
    town: null,
    species: 'raven',
    coat: 'raven',
    role: 'wanderer',
    lines: [
      'Standing stones are older than anyone. Nobody knows who put them there.',
      'I sit on them. Feels important.',
      "Something under the middle one. Never dug. Wouldn't dare.",
    ],
  },
  {
    id: 'willow',
    name: 'Willow',
    town: null,
    species: 'deer',
    coat: 'cream',
    role: 'wanderer',
    lines: [
      "The river's the oldest road there is.",
      'Follow it far enough and you get to the sea.',
      'Follow it the other way and you get wet.',
    ],
  },
  {
    id: 'sorrel',
    name: 'Sorrel',
    town: null,
    species: 'fox',
    coat: 'ginger',
    role: 'wanderer',
    lines: [
      "Lost? Everyone's lost round here at first.",
      'Towns are: there, there, over that hill, and the one nobody can find.',
      "You'll find it. Or you won't. Either's fine.",
    ],
  },
  {
    id: 'birch',
    name: 'Birch',
    town: null,
    species: 'squirrel',
    coat: 'grey',
    role: 'wanderer',
    lines: [
      "Woods go on further than you'd think.",
      "I've never reached the end of them. I've tried twice.",
      "Third time's planned for spring.",
    ],
  },
  {
    id: 'peat',
    name: 'Peat',
    town: null,
    species: 'badger',
    coat: 'grey',
    role: 'wanderer',
    lines: [
      "Down there's my sett. No, you can't see it.",
      "Digging's honest work. Nobody appreciates it.",
      'If you ever need a hole, you know where I am.',
    ],
  },
  {
    id: 'meadow',
    name: 'Meadow',
    town: null,
    species: 'sheep',
    coat: 'white',
    role: 'farmer',
    lines: [
      'Grass is good this year. Really is.',
      "That's the whole update. Grass. Good.",
      'See you tomorrow, probably.',
    ],
  },
  {
    id: 'tansy',
    name: 'Tansy',
    town: null,
    species: 'cat',
    coat: 'calico',
    role: 'wanderer',
    lines: [
      "Another one on two legs! We're rarer than you'd think.",
      'Most of my cousins never bothered standing up. Their loss.',
      "A cafe full of cats. That's either genius or a fire hazard.",
    ],
  },
  {
    id: 'dill',
    name: 'Dill',
    town: null,
    species: 'frog',
    coat: 'green',
    role: 'wanderer',
    lines: [
      'Damp today. Excellent.',
      "You want to talk to the birds about the taxi thing. They're organised.",
      "Not me. I hop. It's slower but it's dignified.",
    ],
  },
  {
    id: 'ash',
    name: 'Ash',
    town: null,
    species: 'owl',
    coat: 'owl',
    role: 'wanderer',
    lines: [
      "Night's the best of it. All this, and nobody about.",
      'Lamps make a village look like a handful of coals from up here.',
      'You should light your cafe properly. It shows from the hill.',
    ],
  },
  {
    id: 'quire',
    name: 'Quire',
    town: 'brambleford',
    species: 'owl',
    coat: 'owl',
    role: 'library',
    when: 'always',
    lines: [
      "Shhh. Well — there's nobody else in. Talk as loud as you like.",
      'Everything ever written about this valley is on that middle shelf. It is not a long shelf.',
      "People think a library is about books. It's about knowing which one.",
    ],
    hint: 'Anything old around here, you want the town history. Middle shelf. Green spine, gold letters.',
  },
  {
    id: 'moth',
    name: 'Moth',
    town: 'brambleford',
    species: 'mouse',
    coat: 'grey',
    role: 'villager',
    when: 'night',
    lines: [
      "Don't mind me. I'm counting.",
      'Fourteen species on that one lamp last night. Fourteen!',
      "Everyone's asleep and missing all of it.",
    ],
  },
  {
    id: 'pike',
    name: 'Pike',
    town: 'brambleford',
    species: 'hedgehog',
    coat: 'grey',
    role: 'villager',
    when: 'night',
    lines: [
      'Night watch. Self-appointed. Nobody asked, nobody has complained.',
      "Quiet tonight. Quiet's good. Quiet means the job is going well.",
      'Careful down by the hedges after midnight. No reason.',
    ],
  },
  {
    id: 'woofers',
    name: 'Sir Woofers',
    town: 'brambleford',
    species: 'dog',
    coat: 'white',
    cloth: '#a8c8e8',
    role: 'ghost',
    note: 'Nobody sees him until they have looked in the hedge and told Button what they saw. A ghost dog ambling up the lane every night in plain view is not something anybody needs to discover.',
    when: 'night',
    spot: 'bushes',
    ghost: true,
    secret: { quest: 'lane_end_hedge', step: 1 },
    lines: [
      '*an extremely old dog, made mostly of moonlight, snuffling along the hedge*',
      'I have lost something. I have been losing it for rather a long time.',
      'It was gold. It was mine. They put my name on it.',
    ],
  },
  {
    id: 'vesper',
    name: 'Vesper',
    town: 'hollowdown',
    species: 'raven',
    coat: 'raven',
    role: 'villager',
    when: 'night',
    lines: [
      'Best view in the valley, and it only opens at night.',
      'You can see every lit window from up here. I know whose is whose.',
      "Stars are other people's lamps. That isn't true. I like saying it.",
    ],
    hint: 'Stand in the middle of the standing stones after dark. Just stand there. You will see.',
  },
  {
    id: 'tallow',
    name: 'Tallow',
    town: 'thistlewick',
    species: 'goat',
    coat: 'cream',
    role: 'villager',
    when: 'night',
    lines: [
      'Wax sets better in the cold, so I work in the cold.',
      "Every candle in the valley, me. You're welcome.",
      'A lit window is an invitation. Put one in that cafe of yours.',
    ],
  },
  {
    id: 'brine',
    name: 'Brine',
    town: 'saltmere',
    species: 'otter',
    coat: 'brown',
    role: 'villager',
    when: 'night',
    lines: [
      'Night fishing. Better catch, worse company. Present company excepted.',
      'That old pier is rotten through. Mind your feet if you go out on it.',
      'The tide takes things out and brings other things back. Never the same things.',
    ],
    hint: 'Anything lost off the end of that pier is still under it. The mud keeps what it is given.',
  },
  {
    id: 'bruin',
    name: 'Bruin',
    species: 'bear',
    coat: 'white',
    role: 'villager',
    when: 'night',
    regular: true,
    seat: 'barStool',
    lines: [
      'I do not queue. Queueing is for people with somewhere to be.',
      'What do you call a raven who works nights? A crow-nological anomaly. ...You laughed. Slightly.',
      'A pun is a small unkindness you do to a word. The word forgives you. Usually.',
      'Warm room. Cats. Somebody who will listen. I have made worse decisions than this one.',
    ],
    hint: 'There is a contest. Longest Face Wins, they call it. Whoever hears the most puns without laughing. I have not won it in four years and I intend to lose again with style.',
  },
  {
    id: 'comfrey',
    name: 'Comfrey',
    species: 'goat',
    coat: 'cream',
    role: 'villager',
    regular: true,
    tellsFirst: true,
    arrives: { deliveries: 10, until: 'heard_hint_comfrey' },
    lines: [
      'I have seen you on that road more than the road has seen itself.',
      'There is a faster way about this valley. It has fur on it.',
      'Ask for Bell. Everyone in Thistlewick knows Bell.',
    ],
    hint: 'You are wearing that road out. Drover Bell is in Thistlewick with a riding bear for sale — daylight hours, by the market. She is not cheap and she is worth it.',
  },
  {
    id: 'bell',
    name: 'Drover Bell',
    town: 'thistlewick',
    species: 'badger',
    coat: 'badger',
    role: 'villager',
    note: 'Not standing about in the market until somebody has told you she exists: a bear for sale is not something you walk past and fail to notice.',
    sells: 'bear',
    secret: { flag: 'heard_hint_comfrey' },
    lines: [
      'She is not a horse. Do not ride her like a horse.',
      'One fish a day. Fresh. She will tell you if you forget, and you will not enjoy being told.',
      'Water does not stop her. Very little does.',
    ],
    sold: [
      'She is yours. Feed her and she will take you anywhere.',
      'How is she? Eating? Good. That is the whole of it.',
    ],
  },
  {
    id: 'fennel',
    name: 'Fennel',
    species: 'rabbit',
    coat: 'cream',
    role: 'villager',
    regular: true,
    visitChance: 0.45,
    lines: [
      'I have a job. Afternoons. It is not a demanding job and I am not a demanding man.',
      'Do you have the cordial? You do not have the cordial. That is fine. I will wait.',
      "I could go and get it myself, yes. I could. Let's both sit with that for a moment.",
      '*settles into the nearest chair with the finality of a dropped sandbag*',
    ],
    hint: 'Root & Remedy. Oakhollow. Ask for the cordial and do not let them talk you into the tea.',
  },
  {
    id: 'linnet',
    name: 'Linnet',
    species: 'deer',
    coat: 'brown',
    role: 'villager',
    when: 'night',
    regular: true,
    visitChance: 0.42,
    lines: [
      'I come for the grey one. I am not going to pretend otherwise.',
      'She used to sit with me. Every night, same chair. Then she stopped.',
      'I have not done anything. I have been over it a great many times.',
      "It's a nice room. It would be a nicer room with her in it.",
    ],
  },
  {
    id: 'pim',
    name: 'Pim',
    town: 'saltmere',
    species: 'owl',
    coat: 'owl',
    role: 'villager',
    when: 'night',
    lines: [
      "There's someone I keep meaning to speak to. I keep meaning it very hard.",
      'The trouble is they all look the same to me. No — that came out badly. I mean the birds.',
      'I have rehearsed an opening line for eleven months. It is not a good one.',
    ],
  },
  {
    id: 'nutmeg',
    name: 'Nutmeg',
    town: 'thistlewick',
    species: 'mouse',
    coat: 'brown',
    role: 'villager',
    when: 'night',
    lines: [
      'I have a job. It is at the mill. It mostly involves being at the mill.',
      "Warm milk. That's the order. It's always the order. Don't make me look at the board.",
      '*asleep, upright, with the composure of someone who has practised*',
    ],
    hint: 'A cafe that is warm at two in the morning would be, I think, the finest thing in the valley.',
  },
  {
    id: 'nightjar',
    name: 'Nightjar',
    species: 'songbird',
    coat: 'grey',
    role: 'wanderer',
    when: 'night',
    lines: [
      '*a long whirring churr, somewhere between a bird and a distant engine*',
      'You are a long way from your lamp.',
      "I go where it's dark. That's most places, if you are patient.",
    ],
  },
];